/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.apis.MtnManagerApi
import com.mtnmanager.sdk.models.Amenity
import com.mtnmanager.sdk.models.FullReport
import com.mtnmanager.sdk.models.Lift
import com.mtnmanager.sdk.models.MobileAppResponse
import com.mtnmanager.sdk.models.OperatingHours
import com.mtnmanager.sdk.models.Overview
import com.mtnmanager.sdk.models.ParkingLot
import com.mtnmanager.sdk.models.Run
import com.mtnmanager.sdk.models.SnowReport
import com.mtnmanager.sdk.models.SummerTrail
import com.mtnmanager.sdk.models.TerrainPark
import com.mtnmanager.sdk.models.TrailMap
import com.mtnmanager.sdk.models.TrailMapSummary
import com.mtnmanager.sdk.models.Weather
import com.mtnmanager.sdk.models.Webcam
import com.mtnmanager.sdk.models.WebcamHistoryResponse

class MtnManagerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MtnManagerApi
        //val apiInstance = MtnManagerApi()

        // to test getAmenities
        should("test getAmenities") {
            // uncomment below to test getAmenities
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<Amenity> = apiInstance.getAmenities(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getFullReport
        should("test getFullReport") {
            // uncomment below to test getFullReport
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : FullReport = apiInstance.getFullReport(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getHours
        should("test getHours") {
            // uncomment below to test getHours
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : OperatingHours = apiInstance.getHours(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getLifts
        should("test getLifts") {
            // uncomment below to test getLifts
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<Lift> = apiInstance.getLifts(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getMobileApp
        should("test getMobileApp") {
            // uncomment below to test getMobileApp
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : MobileAppResponse = apiInstance.getMobileApp(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getOverview
        should("test getOverview") {
            // uncomment below to test getOverview
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : Overview = apiInstance.getOverview(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getParkingLots
        should("test getParkingLots") {
            // uncomment below to test getParkingLots
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<ParkingLot> = apiInstance.getParkingLots(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getRuns
        should("test getRuns") {
            // uncomment below to test getRuns
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<Run> = apiInstance.getRuns(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getSnow
        should("test getSnow") {
            // uncomment below to test getSnow
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<SnowReport> = apiInstance.getSnow(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getSummerTrails
        should("test getSummerTrails") {
            // uncomment below to test getSummerTrails
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<SummerTrail> = apiInstance.getSummerTrails(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getTerrainParks
        should("test getTerrainParks") {
            // uncomment below to test getTerrainParks
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<TerrainPark> = apiInstance.getTerrainParks(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getTrailMap
        should("test getTrailMap") {
            // uncomment below to test getTrailMap
            //val uuid : kotlin.String = uuid_example // kotlin.String | Resource UUID
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : TrailMap = apiInstance.getTrailMap(uuid, acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getTrailMaps
        should("test getTrailMaps") {
            // uncomment below to test getTrailMaps
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<TrailMapSummary> = apiInstance.getTrailMaps(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getWeather
        should("test getWeather") {
            // uncomment below to test getWeather
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<Weather> = apiInstance.getWeather(acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getWebcamHistory
        should("test getWebcamHistory") {
            // uncomment below to test getWebcamHistory
            //val uuid : kotlin.String = uuid_example // kotlin.String | Resource UUID
            //val from : kotlin.String = from_example // kotlin.String | Inclusive lower bound on `captured_at` (RFC 3339).
            //val to : kotlin.String = to_example // kotlin.String | Inclusive upper bound on `captured_at` (RFC 3339).
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : WebcamHistoryResponse = apiInstance.getWebcamHistory(uuid, from, to, acceptLanguage)
            //result shouldBe ("TODO")
        }

        // to test getWebcams
        should("test getWebcams") {
            // uncomment below to test getWebcams
            //val acceptLanguage : kotlin.String = fr-CA // kotlin.String | Preferred language and optional region for human-readable strings in the response (e.g. operating hours summaries). Supports `en`, `fr`, `de`, `it`, and `es`, with optional region tags such as `fr-CA` or `de-CH`. Defaults to English when omitted or unsupported.
            //val result : kotlin.collections.List<Webcam> = apiInstance.getWebcams(acceptLanguage)
            //result shouldBe ("TODO")
        }

    }
}
