/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Category classification for amenities
 *
 * Values: restaurant,coffee,bar,tubing,ski_school,rental_shop,daycare,ticketing,lodge,hotel,lockers,retail,other
 */

@JsonClass(generateAdapter = false)
enum class AmenityCategory(val value: kotlin.String) {

    @Json(name = "restaurant")
    restaurant("restaurant"),

    @Json(name = "coffee")
    coffee("coffee"),

    @Json(name = "bar")
    bar("bar"),

    @Json(name = "tubing")
    tubing("tubing"),

    @Json(name = "ski_school")
    ski_school("ski_school"),

    @Json(name = "rental_shop")
    rental_shop("rental_shop"),

    @Json(name = "daycare")
    daycare("daycare"),

    @Json(name = "ticketing")
    ticketing("ticketing"),

    @Json(name = "lodge")
    lodge("lodge"),

    @Json(name = "hotel")
    hotel("hotel"),

    @Json(name = "lockers")
    lockers("lockers"),

    @Json(name = "retail")
    retail("retail"),

    @Json(name = "other")
    other("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AmenityCategory) "$data" else null

        /**
         * Returns a valid [AmenityCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AmenityCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

