/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.AmenityCategory

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * Amenity entry within a CalendarDay, showing per-amenity hours for a specific date.
 *
 * @param uuid Amenity UUID.
 * @param name Amenity name.
 * @param category Amenity category.
 * @param opensAt Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day.
 * @param closesAt Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day.
 */
@Serializable

data class AmenityCalendarEntry (

    /* Amenity UUID. */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* Amenity name. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* Amenity category. */
    @Contextual @SerialName(value = "category")
    val category: AmenityCategory,

    /* Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day. */
    @SerialName(value = "opens_at")
    val opensAt: kotlin.String? = null,

    /* Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day. */
    @SerialName(value = "closes_at")
    val closesAt: kotlin.String? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (category.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

