/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * Category classification for amenities
 *
 * Values: restaurant,coffee,bar,tubing,ski_school,rental_shop,daycare,ticketing,lodge,hotel,lockers,retail,other,unknown_default_open_api
 */
@Serializable(with = AmenityCategorySerializer::class)
enum class AmenityCategory(val value: kotlin.String) {

    @SerialName(value = "restaurant")
    restaurant("restaurant"),

    @SerialName(value = "coffee")
    coffee("coffee"),

    @SerialName(value = "bar")
    bar("bar"),

    @SerialName(value = "tubing")
    tubing("tubing"),

    @SerialName(value = "ski_school")
    ski_school("ski_school"),

    @SerialName(value = "rental_shop")
    rental_shop("rental_shop"),

    @SerialName(value = "daycare")
    daycare("daycare"),

    @SerialName(value = "ticketing")
    ticketing("ticketing"),

    @SerialName(value = "lodge")
    lodge("lodge"),

    @SerialName(value = "hotel")
    hotel("hotel"),

    @SerialName(value = "lockers")
    lockers("lockers"),

    @SerialName(value = "retail")
    retail("retail"),

    @SerialName(value = "other")
    other("other"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AmenityCategory) "$data" else null

        /**
         * Returns a valid [AmenityCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AmenityCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object AmenityCategorySerializer : KSerializer<AmenityCategory> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): AmenityCategory {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return AmenityCategory.entries.firstOrNull { it.value == value }
            ?: AmenityCategory.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: AmenityCategory) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


