/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.AmenityCategory
import com.mtnmanager.sdk.models.Schedule

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Amenity schedule for the OperatingHours response
 *
 * @param uuid Amenity UUID
 * @param name Amenity name
 * @param category Amenity category
 * @param schedules Operating schedules for this amenity
 */


data class AmenitySchedule (

    /* Amenity UUID */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* Amenity name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Amenity category */
    @Json(name = "category")
    val category: AmenityCategory,

    /* Operating schedules for this amenity */
    @Json(name = "schedules")
    val schedules: kotlin.collections.List<Schedule>

) {


}

