/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.AmenityCategory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Amenity entry within a CalendarDay, showing per-amenity hours for a specific date.
 *
 * @param uuid Amenity UUID.
 * @param name Amenity name.
 * @param category Amenity category.
 * @param opensAt Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day.
 * @param closesAt Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day.
 */


data class AmenityCalendarEntry (

    /* Amenity UUID. */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* Amenity name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Amenity category. */
    @Json(name = "category")
    val category: AmenityCategory,

    /* Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day. */
    @Json(name = "opens_at")
    val opensAt: kotlin.String? = null,

    /* Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day. */
    @Json(name = "closes_at")
    val closesAt: kotlin.String? = null

) {


}

