/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * App-level configuration bundled into the aggregated report.
 *
 * @param hostedBaseUrl The resort's hosted base URL — scheme + host with no path, e.g.  `https://powder-mountain.mtnmanager.net`, or the resort's own custom  domain when one is configured.
 * @param trailMapAssetsUpdatedAt Last time the static trail-map assets were re-published, ISO 8601 UTC.  Bumped when those assets change so clients can cache-bust.
 */
@Serializable

data class AppConfig (

    /* The resort's hosted base URL — scheme + host with no path, e.g.  `https://powder-mountain.mtnmanager.net`, or the resort's own custom  domain when one is configured. */
    @SerialName(value = "hosted_base_url")
    val hostedBaseUrl: kotlin.String,

    /* Last time the static trail-map assets were re-published, ISO 8601 UTC.  Bumped when those assets change so clients can cache-bust. */
    @SerialName(value = "trail_map_assets_updated_at")
    val trailMapAssetsUpdatedAt: kotlin.String

) {


}

