/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.AmenityCalendarEntry
import com.mtnmanager.sdk.models.ClosureReason
import com.mtnmanager.sdk.models.DayOfWeek

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Operating hours for a specific calendar date.   Represents the calculated open/close times for a single day, combining  information from recurring schedules and any single-day overrides.
 *
 * @param date Calendar date (YYYY-MM-DD).
 * @param dayOfWeek Day of the week.
 * @param isOpen Whether the resort is open on this day.
 * @param opensAt Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
 * @param closesAt Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
 * @param closureReason Optional reason code for closure.
 * @param specialEvent Special event for this day.
 * @param amenities Per-amenity hours for this day. Only included when amenity hours are configured.
 */
@Serializable

data class CalendarDay (

    /* Calendar date (YYYY-MM-DD). */
    @Contextual @SerialName(value = "date")
    val date: java.time.LocalDate,

    /* Day of the week. */
    @Contextual @SerialName(value = "day_of_week")
    val dayOfWeek: DayOfWeek,

    /* Whether the resort is open on this day. */
    @SerialName(value = "is_open")
    val isOpen: kotlin.Boolean,

    /* Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day. */
    @SerialName(value = "opens_at")
    val opensAt: kotlin.String? = null,

    /* Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day. */
    @SerialName(value = "closes_at")
    val closesAt: kotlin.String? = null,

    /* Optional reason code for closure. */
    @Contextual @SerialName(value = "closure_reason")
    val closureReason: ClosureReason? = null,

    /* Special event for this day. */
    @SerialName(value = "special_event")
    val specialEvent: kotlin.String? = null,

    /* Per-amenity hours for this day. Only included when amenity hours are configured. */
    @SerialName(value = "amenities")
    val amenities: kotlin.collections.List<AmenityCalendarEntry>? = null

) {


}

