/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.CurrentWeatherImperial
import com.mtnmanager.sdk.models.CurrentWeatherMetric
import com.mtnmanager.sdk.models.WeatherConditionCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Current weather conditions with both metric and imperial units
 *
 * @param imperial Measurements in imperial units
 * @param metric Measurements in metric units
 * @param condition Human-readable weather condition
 * @param conditionCode Weather condition code
 * @param timestamp Timestamp of observation
 * @param windDirection Wind direction in degrees (0-360)
 * @param windDirectionCardinal Wind direction as cardinal direction (N, NE, E, SE, S, SW, W, NW)
 */
@Serializable

data class CurrentWeather (

    /* Measurements in imperial units */
    @SerialName(value = "imperial")
    val imperial: CurrentWeatherImperial,

    /* Measurements in metric units */
    @SerialName(value = "metric")
    val metric: CurrentWeatherMetric,

    /* Human-readable weather condition */
    @SerialName(value = "condition")
    val condition: kotlin.String,

    /* Weather condition code */
    @Contextual @SerialName(value = "condition_code")
    val conditionCode: WeatherConditionCode,

    /* Timestamp of observation */
    @Contextual @SerialName(value = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* Wind direction in degrees (0-360) */
    @SerialName(value = "wind_direction")
    val windDirection: kotlin.Int? = null,

    /* Wind direction as cardinal direction (N, NE, E, SE, S, SW, W, NW) */
    @SerialName(value = "wind_direction_cardinal")
    val windDirectionCardinal: kotlin.String? = null

) {


}

