/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Current temperature and precipitation measurements in imperial units
 *
 * @param temperature Temperature in Fahrenheit
 * @param feelsLike Feels like temperature in Fahrenheit
 * @param windSpeed Wind speed in mph
 * @param snowfall Snowfall in inches
 * @param precipitation Precipitation in inches
 * @param windGust Wind gust in mph
 */
@Serializable

data class CurrentWeatherImperial (

    /* Temperature in Fahrenheit */
    @SerialName(value = "temperature")
    val temperature: kotlin.Int,

    /* Feels like temperature in Fahrenheit */
    @SerialName(value = "feels_like")
    val feelsLike: kotlin.Int,

    /* Wind speed in mph */
    @SerialName(value = "wind_speed")
    val windSpeed: kotlin.Int,

    /* Snowfall in inches */
    @SerialName(value = "snowfall")
    val snowfall: kotlin.Int? = null,

    /* Precipitation in inches */
    @SerialName(value = "precipitation")
    val precipitation: kotlin.Int? = null,

    /* Wind gust in mph */
    @SerialName(value = "wind_gust")
    val windGust: kotlin.Int? = null

) {


}

