/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Current temperature and precipitation measurements in metric units
 *
 * @param temperature Temperature in Celsius
 * @param feelsLike Feels like temperature in Celsius
 * @param windSpeed Wind speed in km/h
 * @param snowfall Snowfall in centimeters
 * @param precipitation Precipitation in millimeters
 * @param windGust Wind gust in km/h
 */
@Serializable

data class CurrentWeatherMetric (

    /* Temperature in Celsius */
    @SerialName(value = "temperature")
    val temperature: kotlin.Int,

    /* Feels like temperature in Celsius */
    @SerialName(value = "feels_like")
    val feelsLike: kotlin.Int,

    /* Wind speed in km/h */
    @SerialName(value = "wind_speed")
    val windSpeed: kotlin.Int,

    /* Snowfall in centimeters */
    @SerialName(value = "snowfall")
    val snowfall: kotlin.Int? = null,

    /* Precipitation in millimeters */
    @SerialName(value = "precipitation")
    val precipitation: kotlin.Int? = null,

    /* Wind gust in km/h */
    @SerialName(value = "wind_gust")
    val windGust: kotlin.Int? = null

) {


}

