/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Daily forecast measurements in imperial units
 *
 * @param temperatureHigh High temperature in Fahrenheit
 * @param temperatureLow Low temperature in Fahrenheit
 * @param snowfallTotal Total snowfall expected in inches
 * @param precipitationTotal Total precipitation expected in inches
 * @param windSpeedMax Maximum wind speed in mph
 * @param windGustMax Maximum wind gust in mph
 */
@Serializable

data class DailyForecastImperial (

    /* High temperature in Fahrenheit */
    @SerialName(value = "temperature_high")
    val temperatureHigh: kotlin.Int,

    /* Low temperature in Fahrenheit */
    @SerialName(value = "temperature_low")
    val temperatureLow: kotlin.Int,

    /* Total snowfall expected in inches */
    @SerialName(value = "snowfall_total")
    val snowfallTotal: kotlin.Int? = null,

    /* Total precipitation expected in inches */
    @SerialName(value = "precipitation_total")
    val precipitationTotal: kotlin.Int? = null,

    /* Maximum wind speed in mph */
    @SerialName(value = "wind_speed_max")
    val windSpeedMax: kotlin.Int? = null,

    /* Maximum wind gust in mph */
    @SerialName(value = "wind_gust_max")
    val windGustMax: kotlin.Int? = null

) {


}

