/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.DailyForecastImperial
import com.mtnmanager.sdk.models.DailyForecastMetric
import com.mtnmanager.sdk.models.WeatherConditionCode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Daily weather summary with both unit systems
 *
 * @param date Date of forecast (YYYY-MM-DD format)
 * @param imperial Measurements in imperial units
 * @param metric Measurements in metric units
 * @param condition Human-readable condition
 * @param conditionCode Condition code
 * @param sunrise Sunrise time
 * @param sunset Sunset time
 * @param precipitationProbability Probability of precipitation (0-100%)
 */


data class DailyForecast (

    /* Date of forecast (YYYY-MM-DD format) */
    @Json(name = "date")
    val date: java.time.LocalDate,

    /* Measurements in imperial units */
    @Json(name = "imperial")
    val imperial: DailyForecastImperial,

    /* Measurements in metric units */
    @Json(name = "metric")
    val metric: DailyForecastMetric,

    /* Human-readable condition */
    @Json(name = "condition")
    val condition: kotlin.String,

    /* Condition code */
    @Json(name = "condition_code")
    val conditionCode: WeatherConditionCode,

    /* Sunrise time */
    @Json(name = "sunrise")
    val sunrise: java.time.OffsetDateTime,

    /* Sunset time */
    @Json(name = "sunset")
    val sunset: java.time.OffsetDateTime,

    /* Probability of precipitation (0-100%) */
    @Json(name = "precipitation_probability")
    val precipitationProbability: kotlin.Int? = null

) {


}

