/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Daily forecast measurements in imperial units
 *
 * @param temperatureHigh High temperature in Fahrenheit
 * @param temperatureLow Low temperature in Fahrenheit
 * @param snowfallTotal Total snowfall expected in inches
 * @param precipitationTotal Total precipitation expected in inches
 * @param windSpeedMax Maximum wind speed in mph
 * @param windGustMax Maximum wind gust in mph
 */


data class DailyForecastImperial (

    /* High temperature in Fahrenheit */
    @Json(name = "temperature_high")
    val temperatureHigh: kotlin.Int,

    /* Low temperature in Fahrenheit */
    @Json(name = "temperature_low")
    val temperatureLow: kotlin.Int,

    /* Total snowfall expected in inches */
    @Json(name = "snowfall_total")
    val snowfallTotal: kotlin.Int? = null,

    /* Total precipitation expected in inches */
    @Json(name = "precipitation_total")
    val precipitationTotal: kotlin.Int? = null,

    /* Maximum wind speed in mph */
    @Json(name = "wind_speed_max")
    val windSpeedMax: kotlin.Int? = null,

    /* Maximum wind gust in mph */
    @Json(name = "wind_gust_max")
    val windGustMax: kotlin.Int? = null

) {


}

