/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Daily forecast measurements in metric units
 *
 * @param temperatureHigh High temperature in Celsius
 * @param temperatureLow Low temperature in Celsius
 * @param snowfallTotal Total snowfall expected in centimeters
 * @param precipitationTotal Total precipitation expected in millimeters
 * @param windSpeedMax Maximum wind speed in km/h
 * @param windGustMax Maximum wind gust in km/h
 */
@Serializable

data class DailyForecastMetric (

    /* High temperature in Celsius */
    @SerialName(value = "temperature_high")
    val temperatureHigh: kotlin.Int,

    /* Low temperature in Celsius */
    @SerialName(value = "temperature_low")
    val temperatureLow: kotlin.Int,

    /* Total snowfall expected in centimeters */
    @SerialName(value = "snowfall_total")
    val snowfallTotal: kotlin.Int? = null,

    /* Total precipitation expected in millimeters */
    @SerialName(value = "precipitation_total")
    val precipitationTotal: kotlin.Int? = null,

    /* Maximum wind speed in km/h */
    @SerialName(value = "wind_speed_max")
    val windSpeedMax: kotlin.Int? = null,

    /* Maximum wind gust in km/h */
    @SerialName(value = "wind_gust_max")
    val windGustMax: kotlin.Int? = null

) {


}

