/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.DailyForecastImperial
import com.mtnmanager.sdk.models.DailyForecastMetric
import com.mtnmanager.sdk.models.WeatherConditionCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * Daily weather summary with both unit systems
 *
 * @param date Date of forecast (YYYY-MM-DD format)
 * @param imperial Measurements in imperial units
 * @param metric Measurements in metric units
 * @param condition Human-readable condition
 * @param conditionCode Condition code
 * @param sunrise Sunrise time
 * @param sunset Sunset time
 * @param precipitationProbability Probability of precipitation (0-100%)
 */
@Serializable

data class DailyForecast (

    /* Date of forecast (YYYY-MM-DD format) */
    @Contextual @SerialName(value = "date")
    val date: java.time.LocalDate,

    /* Measurements in imperial units */
    @SerialName(value = "imperial")
    val imperial: DailyForecastImperial,

    /* Measurements in metric units */
    @SerialName(value = "metric")
    val metric: DailyForecastMetric,

    /* Human-readable condition */
    @SerialName(value = "condition")
    val condition: kotlin.String,

    /* Condition code */
    @Contextual @SerialName(value = "condition_code")
    val conditionCode: WeatherConditionCode,

    /* Sunrise time */
    @Contextual @SerialName(value = "sunrise")
    val sunrise: java.time.OffsetDateTime,

    /* Sunset time */
    @Contextual @SerialName(value = "sunset")
    val sunset: java.time.OffsetDateTime,

    /* Probability of precipitation (0-100%) */
    @SerialName(value = "precipitation_probability")
    val precipitationProbability: kotlin.Int? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (conditionCode.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

