/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.GeoPoint

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Lat/lng bounding box and centroid for a trail map's georeferenced area.
 *
 * @param minLat 
 * @param maxLat 
 * @param minLng 
 * @param maxLng 
 * @param center 
 */
@Serializable

data class GeoBounds (

    @SerialName(value = "min_lat")
    val minLat: kotlin.Double,

    @SerialName(value = "max_lat")
    val maxLat: kotlin.Double,

    @SerialName(value = "min_lng")
    val minLng: kotlin.Double,

    @SerialName(value = "max_lng")
    val maxLng: kotlin.Double,

    @SerialName(value = "center")
    val center: GeoPoint

) {


}

