/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pixelX 
 * @param pixelY 
 * @param lat 
 * @param lng 
 */


data class GeoControlPoint (

    @Json(name = "pixel_x")
    val pixelX: kotlin.Double,

    @Json(name = "pixel_y")
    val pixelY: kotlin.Double,

    @Json(name = "lat")
    val lat: kotlin.Double,

    @Json(name = "lng")
    val lng: kotlin.Double

) {


}

