/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Hourly forecast measurements in imperial units
 *
 * @param temperature Temperature in Fahrenheit
 * @param windSpeed Wind speed in mph
 * @param feelsLike Feels like temperature in Fahrenheit
 * @param snowfall Snowfall amount expected this hour in inches
 * @param precipitation Precipitation amount expected this hour in inches
 * @param windGust Wind gust in mph
 */


data class HourlyForecastImperial (

    /* Temperature in Fahrenheit */
    @Json(name = "temperature")
    val temperature: kotlin.Int,

    /* Wind speed in mph */
    @Json(name = "wind_speed")
    val windSpeed: kotlin.Int,

    /* Feels like temperature in Fahrenheit */
    @Json(name = "feels_like")
    val feelsLike: kotlin.Int? = null,

    /* Snowfall amount expected this hour in inches */
    @Json(name = "snowfall")
    val snowfall: kotlin.Int? = null,

    /* Precipitation amount expected this hour in inches */
    @Json(name = "precipitation")
    val precipitation: kotlin.Int? = null,

    /* Wind gust in mph */
    @Json(name = "wind_gust")
    val windGust: kotlin.Int? = null

) {


}

