/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.HourlyForecastImperial
import com.mtnmanager.sdk.models.HourlyForecastMetric
import com.mtnmanager.sdk.models.WeatherConditionCode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Hourly weather forecast entry with both metric and imperial units
 *
 * @param timestamp Forecast timestamp
 * @param imperial Measurements in imperial units
 * @param metric Measurements in metric units
 * @param condition Human-readable condition
 * @param conditionCode Weather condition code
 * @param precipitationProbability Probability of precipitation (0-100%)
 */


data class HourlyForecast (

    /* Forecast timestamp */
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    /* Measurements in imperial units */
    @Json(name = "imperial")
    val imperial: HourlyForecastImperial,

    /* Measurements in metric units */
    @Json(name = "metric")
    val metric: HourlyForecastMetric,

    /* Human-readable condition */
    @Json(name = "condition")
    val condition: kotlin.String,

    /* Weather condition code */
    @Json(name = "condition_code")
    val conditionCode: WeatherConditionCode,

    /* Probability of precipitation (0-100%) */
    @Json(name = "precipitation_probability")
    val precipitationProbability: kotlin.Int? = null

) {


}

