/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Type of ski lift
 *
 * Values: gondola,tram,eight_pack,six_pack,quad,triple,double,magic_carpet,t_bar,platter,rope_tow,funicular,other
 */
@Serializable
enum class LiftType(val value: kotlin.String) {

    @SerialName(value = "gondola")
    gondola("gondola"),

    @SerialName(value = "tram")
    tram("tram"),

    @SerialName(value = "eight_pack")
    eight_pack("eight_pack"),

    @SerialName(value = "six_pack")
    six_pack("six_pack"),

    @SerialName(value = "quad")
    quad("quad"),

    @SerialName(value = "triple")
    triple("triple"),

    @SerialName(value = "double")
    double("double"),

    @SerialName(value = "magic_carpet")
    magic_carpet("magic_carpet"),

    @SerialName(value = "t_bar")
    t_bar("t_bar"),

    @SerialName(value = "platter")
    platter("platter"),

    @SerialName(value = "rope_tow")
    rope_tow("rope_tow"),

    @SerialName(value = "funicular")
    funicular("funicular"),

    @SerialName(value = "other")
    other("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LiftType) "$data" else null

        /**
         * Returns a valid [LiftType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LiftType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


