/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A banner shown in the mobile app.
 *
 * @param title 
 * @param uuid 
 * @param subtitle 
 * @param imageUrl Full public URL of the banner image.
 * @param url Destination URL opened when the banner is tapped.
 * @param thumbHash Base64-encoded ThumbHash of the banner image, for rendering a blurred  placeholder while the full image loads.
 */


data class MobileAppBanner (

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "uuid")
    val uuid: kotlin.String,

    @Json(name = "subtitle")
    val subtitle: kotlin.String,

    /* Full public URL of the banner image. */
    @Json(name = "image_url")
    val imageUrl: kotlin.String,

    /* Destination URL opened when the banner is tapped. */
    @Json(name = "url")
    val url: kotlin.String,

    /* Base64-encoded ThumbHash of the banner image, for rendering a blurred  placeholder while the full image loads. */
    @Json(name = "thumb_hash")
    val thumbHash: kotlin.String

) {


}

