/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.MobileAppBanner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Aggregated mobile-app data for the resort. New mobile-app surface area is  added as additional fields on this response.
 *
 * @param banners Banners shown in the mobile app, in display order.
 */


data class MobileAppResponse (

    /* Banners shown in the mobile app, in display order. */
    @Json(name = "banners")
    val banners: kotlin.collections.List<MobileAppBanner>

) {


}

