/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.AmenitySchedule
import com.mtnmanager.sdk.models.CalendarDay
import com.mtnmanager.sdk.models.Schedule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Resort's operating hours, including the recurring schedule, and list of individual calendar days.
 *
 * @param schedules Recurring operating schedules currently in effect or upcoming.  Excludes single-day overrides and past schedules.
 * @param calendarDays List of all days the resort is open (or a closure override).  Ordered chronologically, spanning from the earliest scheduled date  to the latest scheduled date in the currently defined operating hours.
 * @param amenitySchedules Per-amenity operating schedules. Only included when amenity hours are configured.
 */
@Serializable

data class OperatingHours (

    /* Recurring operating schedules currently in effect or upcoming.  Excludes single-day overrides and past schedules. */
    @SerialName(value = "schedules")
    val schedules: kotlin.collections.List<Schedule>,

    /* List of all days the resort is open (or a closure override).  Ordered chronologically, spanning from the earliest scheduled date  to the latest scheduled date in the currently defined operating hours. */
    @SerialName(value = "calendar_days")
    val calendarDays: kotlin.collections.List<CalendarDay>,

    /* Per-amenity operating schedules. Only included when amenity hours are configured. */
    @SerialName(value = "amenity_schedules")
    val amenitySchedules: kotlin.collections.List<AmenitySchedule>? = null

) {


}

