/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Written news — daily update, announcements, etc.
 *
 * @param raw Raw Markdown source.
 * @param html Rendered HTML (from Markdown).
 * @param updatedAt When the news was last updated.
 */


data class OverviewNews (

    /* Raw Markdown source. */
    @Json(name = "raw")
    val raw: kotlin.String,

    /* Rendered HTML (from Markdown). */
    @Json(name = "html")
    val html: kotlin.String,

    /* When the news was last updated. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

