/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Lift statistics: open/total counts and last-updated timestamp.
 *
 * @param total Total number of lifts at the resort.
 * @param updatedAt When the most recent update to lift status was made.
 * @param `open` Number of lifts currently open.  Not included if the lifts status feature is disabled.
 */


data class OverviewLifts (

    /* Total number of lifts at the resort. */
    @Json(name = "total")
    val total: kotlin.Long,

    /* When the most recent update to lift status was made. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Number of lifts currently open.  Not included if the lifts status feature is disabled. */
    @Json(name = "open")
    val `open`: kotlin.Long? = null

) {


}

