/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Run statistics: open/groomed/total counts, open/total acres, and last-updated timestamp.
 *
 * @param total Total number of runs at the resort.
 * @param updatedAt When the most recent update to run status was made.
 * @param `open` Number of runs currently open.  Not included if the runs status feature is disabled.
 * @param groomed Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled.
 * @param openAcres Total acres of open runs.  Not included if acres are not tracked or the runs status feature is disabled.
 * @param totalAcres Total acres of all runs.  Not included if acres are not tracked.
 */
@Serializable

data class OverviewRuns (

    /* Total number of runs at the resort. */
    @SerialName(value = "total")
    val total: kotlin.Long,

    /* When the most recent update to run status was made. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Number of runs currently open.  Not included if the runs status feature is disabled. */
    @SerialName(value = "open")
    val `open`: kotlin.Long? = null,

    /* Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled. */
    @SerialName(value = "groomed")
    val groomed: kotlin.Long? = null,

    /* Total acres of open runs.  Not included if acres are not tracked or the runs status feature is disabled. */
    @SerialName(value = "open_acres")
    val openAcres: kotlin.Long? = null,

    /* Total acres of all runs.  Not included if acres are not tracked. */
    @SerialName(value = "total_acres")
    val totalAcres: kotlin.Long? = null

) {


}

