/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Terrain park statistics: open/total counts and last-updated timestamp.
 *
 * @param total Total number of terrain parks at the resort.
 * @param updatedAt When the most recent update to terrain park status was made.
 * @param `open` Number of terrain parks currently open.  Not included if the terrain parks status feature is disabled.
 */
@Serializable

data class OverviewTerrainParks (

    /* Total number of terrain parks at the resort. */
    @SerialName(value = "total")
    val total: kotlin.Long,

    /* When the most recent update to terrain park status was made. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Number of terrain parks currently open.  Not included if the terrain parks status feature is disabled. */
    @SerialName(value = "open")
    val `open`: kotlin.Long? = null

) {


}

