/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Run statistics: open/groomed/total counts, open/total acres, and last-updated timestamp.
 *
 * @param total Total number of runs at the resort.
 * @param updatedAt When the most recent update to run status was made.
 * @param `open` Number of runs currently open.  Not included if the runs status feature is disabled.
 * @param groomed Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled.
 * @param openAcres Total acres of open runs.  Not included if acres are not tracked or the runs status feature is disabled.
 * @param totalAcres Total acres of all runs.  Not included if acres are not tracked.
 */


data class OverviewRuns (

    /* Total number of runs at the resort. */
    @Json(name = "total")
    val total: kotlin.Long,

    /* When the most recent update to run status was made. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Number of runs currently open.  Not included if the runs status feature is disabled. */
    @Json(name = "open")
    val `open`: kotlin.Long? = null,

    /* Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled. */
    @Json(name = "groomed")
    val groomed: kotlin.Long? = null,

    /* Total acres of open runs.  Not included if acres are not tracked or the runs status feature is disabled. */
    @Json(name = "open_acres")
    val openAcres: kotlin.Long? = null,

    /* Total acres of all runs.  Not included if acres are not tracked. */
    @Json(name = "total_acres")
    val totalAcres: kotlin.Long? = null

) {


}

