/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.ParkingLotStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a parking lot at the resort with its current status and amenities.
 *
 * @param uuid Unique identifier for the parking lot.
 * @param name Display name of the parking lot.
 * @param slug URL-friendly name of the parking lot.
 * @param status Current status (open, closed, or full).
 * @param shuttle Whether shuttle service is available from this lot.
 * @param paid Whether parking is paid/requires payment.
 * @param reservationRequired Whether a reservation is required to park here.
 * @param updatedAt When this parking lot's information was last updated.
 * @param capacity Maximum vehicle capacity, if set.
 * @param images Images attached to this parking lot, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
 */


data class ParkingLot (

    /* Unique identifier for the parking lot. */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* Display name of the parking lot. */
    @Json(name = "name")
    val name: kotlin.String,

    /* URL-friendly name of the parking lot. */
    @Json(name = "slug")
    val slug: kotlin.String,

    /* Current status (open, closed, or full). */
    @Json(name = "status")
    val status: ParkingLotStatus,

    /* Whether shuttle service is available from this lot. */
    @Json(name = "shuttle")
    val shuttle: kotlin.Boolean,

    /* Whether parking is paid/requires payment. */
    @Json(name = "paid")
    val paid: kotlin.Boolean,

    /* Whether a reservation is required to park here. */
    @Json(name = "reservation_required")
    val reservationRequired: kotlin.Boolean,

    /* When this parking lot's information was last updated. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Maximum vehicle capacity, if set. */
    @Json(name = "capacity")
    val capacity: kotlin.Int? = null,

    /* Images attached to this parking lot, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    @Json(name = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) {


}

