/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.Region
import com.mtnmanager.sdk.models.UnitPreference

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Contains general information about the ski resort and its MtnManager account.
 *
 * @param uuid Unique identifier for the resort.
 * @param name Display name of the resort.
 * @param slug URL-friendly identifier for the resort, used in account subdomain.
 * @param timezone IANA timezone identifier for the resort's local time.
 * @param region Region, affects difficulty icon style.
 * @param unitPreference Preferred unit system for measurements (metric or imperial).
 * @param logoUrl Full public URL to the resort's logo image. `null` if no logo is set.
 */


data class ResortInfo (

    /* Unique identifier for the resort. */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* Display name of the resort. */
    @Json(name = "name")
    val name: kotlin.String,

    /* URL-friendly identifier for the resort, used in account subdomain. */
    @Json(name = "slug")
    val slug: kotlin.String,

    /* IANA timezone identifier for the resort's local time. */
    @Json(name = "timezone")
    val timezone: kotlin.String,

    /* Region, affects difficulty icon style. */
    @Json(name = "region")
    val region: Region,

    /* Preferred unit system for measurements (metric or imperial). */
    @Json(name = "unit_preference")
    val unitPreference: UnitPreference,

    /* Full public URL to the resort's logo image. `null` if no logo is set. */
    @Json(name = "logo_url")
    val logoUrl: kotlin.String? = null

) {


}

