/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.RunDifficulty
import com.mtnmanager.sdk.models.RunStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a single run at the resort with its current status,  grooming information, and difficulty rating.
 *
 * @param uuid Unique identifier for the run.
 * @param name Display name of the run.
 * @param slug URL-friendly name of the run.
 * @param difficulty Difficulty rating of the run.
 * @param status Current operational status (open, closed, or unknown).
 * @param groomedToday Whether the run was groomed within the last 24 hours.
 * @param snowmaking Whether the run has snowmaking capabilities.
 * @param nightSkiing Whether the run is available for night skiing.
 * @param conditionNotes Notes about current conditions on this run.
 * @param updatedAt When this run's information was last updated.
 * @param number Optional run number.
 * @param lastGroomed When the run was last groomed.  `null` if never groomed, or if the runs grooming feature is disabled.
 * @param areaUuid UUID of the area this run belongs to, if assigned.
 * @param areaName Name of the area this run belongs to, if assigned.
 * @param areaDisplayOrder Display order of the area this run belongs to, if assigned, for sorting purposes.
 * @param images Images attached to this run, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
 */
@Serializable

data class Run (

    /* Unique identifier for the run. */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* Display name of the run. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL-friendly name of the run. */
    @SerialName(value = "slug")
    val slug: kotlin.String,

    /* Difficulty rating of the run. */
    @Contextual @SerialName(value = "difficulty")
    val difficulty: RunDifficulty,

    /* Current operational status (open, closed, or unknown). */
    @Contextual @SerialName(value = "status")
    val status: RunStatus,

    /* Whether the run was groomed within the last 24 hours. */
    @SerialName(value = "groomed_today")
    val groomedToday: kotlin.Boolean,

    /* Whether the run has snowmaking capabilities. */
    @SerialName(value = "snowmaking")
    val snowmaking: kotlin.Boolean,

    /* Whether the run is available for night skiing. */
    @SerialName(value = "night_skiing")
    val nightSkiing: kotlin.Boolean,

    /* Notes about current conditions on this run. */
    @SerialName(value = "condition_notes")
    val conditionNotes: kotlin.String,

    /* When this run's information was last updated. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Optional run number. */
    @SerialName(value = "number")
    val number: kotlin.Int? = null,

    /* When the run was last groomed.  `null` if never groomed, or if the runs grooming feature is disabled. */
    @Contextual @SerialName(value = "last_groomed")
    val lastGroomed: java.time.OffsetDateTime? = null,

    /* UUID of the area this run belongs to, if assigned. */
    @SerialName(value = "area_uuid")
    val areaUuid: kotlin.String? = null,

    /* Name of the area this run belongs to, if assigned. */
    @SerialName(value = "area_name")
    val areaName: kotlin.String? = null,

    /* Display order of the area this run belongs to, if assigned, for sorting purposes. */
    @SerialName(value = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null,

    /* Images attached to this run, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    @SerialName(value = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) {


}

