/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Difficulty rating for a ski run.
 *
 * Values: beginner,intermediate,advanced,expert,terrain_park
 */

@JsonClass(generateAdapter = false)
enum class RunDifficulty(val value: kotlin.String) {

    @Json(name = "beginner")
    beginner("beginner"),

    @Json(name = "intermediate")
    intermediate("intermediate"),

    @Json(name = "advanced")
    advanced("advanced"),

    @Json(name = "expert")
    expert("expert"),

    @Json(name = "terrain_park")
    terrain_park("terrain_park");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RunDifficulty) "$data" else null

        /**
         * Returns a valid [RunDifficulty] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RunDifficulty? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

