/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * Operational status of a ski run.
 *
 * Values: `open`,closed,unknown,unknown_default_open_api
 */
@Serializable(with = RunStatusSerializer::class)
enum class RunStatus(val value: kotlin.String) {

    @SerialName(value = "open")
    `open`("open"),

    @SerialName(value = "closed")
    closed("closed"),

    @SerialName(value = "unknown")
    unknown("unknown"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RunStatus) "$data" else null

        /**
         * Returns a valid [RunStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RunStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object RunStatusSerializer : KSerializer<RunStatus> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): RunStatus {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return RunStatus.entries.firstOrNull { it.value == value }
            ?: RunStatus.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: RunStatus) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


