/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.SeasonType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * A season the resort's operating hours define: its type and its days.
 *
 * @param seasonType The season's type (`winter` or `summer`; never `closed`).
 * @param startsOn The season's first day (YYYY-MM-DD), in the resort's local timezone.
 * @param endsOn The season's last day (YYYY-MM-DD), in the resort's local timezone.
 */
@Serializable

data class SeasonPeriod (

    /* The season's type (`winter` or `summer`; never `closed`). */
    @Contextual @SerialName(value = "season_type")
    val seasonType: SeasonType,

    /* The season's first day (YYYY-MM-DD), in the resort's local timezone. */
    @Contextual @SerialName(value = "starts_on")
    val startsOn: java.time.LocalDate,

    /* The season's last day (YYYY-MM-DD), in the resort's local timezone. */
    @Contextual @SerialName(value = "ends_on")
    val endsOn: java.time.LocalDate

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (seasonType.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

