/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.SnowMetrics
import com.mtnmanager.sdk.models.SurfaceCondition

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Provides current snow conditions for a specific area or the entire resort,  including base depth, surface conditions, and snowfall totals in both  metric and imperial units.
 *
 * @param uuid Unique identifier for this snow report.
 * @param conditionNotes Additional notes about current snow conditions, e.g. groomer's notes
 * @param snowfallCm Snowfall accumulation metrics in centimeters.
 * @param snowfallIn Snowfall accumulation metrics in inches.
 * @param reportedAt When this snow report was last updated.
 * @param areaUuid UUID of the area this report covers, if area-specific.  `null` for resort-wide reports.
 * @param areaName Name of the area this report covers, if area-specific.
 * @param areaDisplayOrder Display order of the area this report covers, if area-specific, for sorting purposes.
 * @param baseDepthCm Current base depth in centimeters.  Not included if the base depth feature is disabled.
 * @param baseDepthIn Current base depth in inches.  Not included if the base depth feature is disabled.
 * @param surfaceCondition Primary surface condition using industry standard codes.  Not included if the snow surface condition feature is disabled.   - BS (Bare Spots)  - CO (Corn Snow)  - FG (Frozen Granular)  - HP (Hard Pack)  - IP (Ice Patches)  - IS (Icy Surface)  - LG (Loose Granular)  - MG (Machine Groomed)  - P (Powder)  - PP (Packed Powder)  - SC (Spring Conditions)  - TC (Thin Cover)  - V (Variable)  - WG (Wet Granular)  - WP (Wet Powder)
 * @param secondarySurfaceCondition Secondary surface condition using industry standard codes.  Not included if the secondary snow surface condition feature is disabled.   - BS (Bare Spots)  - CO (Corn Snow)  - FG (Frozen Granular)  - HP (Hard Pack)  - IP (Ice Patches)  - IS (Icy Surface)  - LG (Loose Granular)  - MG (Machine Groomed)  - P (Powder)  - PP (Packed Powder)  - SC (Spring Conditions)  - TC (Thin Cover)  - V (Variable)  - WG (Wet Granular)  - WP (Wet Powder)
 */
@Serializable

data class SnowReport (

    /* Unique identifier for this snow report. */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* Additional notes about current snow conditions, e.g. groomer's notes */
    @SerialName(value = "condition_notes")
    val conditionNotes: kotlin.String,

    /* Snowfall accumulation metrics in centimeters. */
    @SerialName(value = "snowfall_cm")
    val snowfallCm: SnowMetrics,

    /* Snowfall accumulation metrics in inches. */
    @SerialName(value = "snowfall_in")
    val snowfallIn: SnowMetrics,

    /* When this snow report was last updated. */
    @Contextual @SerialName(value = "reported_at")
    val reportedAt: java.time.OffsetDateTime,

    /* UUID of the area this report covers, if area-specific.  `null` for resort-wide reports. */
    @SerialName(value = "area_uuid")
    val areaUuid: kotlin.String? = null,

    /* Name of the area this report covers, if area-specific. */
    @SerialName(value = "area_name")
    val areaName: kotlin.String? = null,

    /* Display order of the area this report covers, if area-specific, for sorting purposes. */
    @SerialName(value = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null,

    /* Current base depth in centimeters.  Not included if the base depth feature is disabled. */
    @SerialName(value = "base_depth_cm")
    val baseDepthCm: kotlin.Int? = null,

    /* Current base depth in inches.  Not included if the base depth feature is disabled. */
    @SerialName(value = "base_depth_in")
    val baseDepthIn: kotlin.Int? = null,

    /* Primary surface condition using industry standard codes.  Not included if the snow surface condition feature is disabled.   - BS (Bare Spots)  - CO (Corn Snow)  - FG (Frozen Granular)  - HP (Hard Pack)  - IP (Ice Patches)  - IS (Icy Surface)  - LG (Loose Granular)  - MG (Machine Groomed)  - P (Powder)  - PP (Packed Powder)  - SC (Spring Conditions)  - TC (Thin Cover)  - V (Variable)  - WG (Wet Granular)  - WP (Wet Powder) */
    @Contextual @SerialName(value = "surface_condition")
    val surfaceCondition: SurfaceCondition? = null,

    /* Secondary surface condition using industry standard codes.  Not included if the secondary snow surface condition feature is disabled.   - BS (Bare Spots)  - CO (Corn Snow)  - FG (Frozen Granular)  - HP (Hard Pack)  - IP (Ice Patches)  - IS (Icy Surface)  - LG (Loose Granular)  - MG (Machine Groomed)  - P (Powder)  - PP (Packed Powder)  - SC (Spring Conditions)  - TC (Thin Cover)  - V (Variable)  - WG (Wet Granular)  - WP (Wet Powder) */
    @Contextual @SerialName(value = "secondary_surface_condition")
    val secondarySurfaceCondition: SurfaceCondition? = null

) {


}

