/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.SummerTrailDifficulty
import com.mtnmanager.sdk.models.SummerTrailStatus
import com.mtnmanager.sdk.models.SummerTrailType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * Represents a single summer trail at the resort with its current status,  type (e.g. hiking, mountain biking), and optional difficulty rating.
 *
 * @param uuid Unique identifier for the trail.
 * @param name Display name of the trail.
 * @param slug URL-friendly name of the trail.
 * @param trailType Type of trail activity (e.g. hiking, mountain_biking). Can have multiple.
 * @param status Current operational status (open, closed, or unknown).
 * @param conditionNotes Notes about current conditions on this trail.
 * @param updatedAt When this trail's information was last updated.
 * @param number Optional trail number.
 * @param difficulty Difficulty rating of the trail (optional for summer trails).
 * @param areaUuid UUID of the area this trail belongs to, if assigned.
 * @param areaName Name of the area this trail belongs to, if assigned.
 * @param areaDisplayOrder Display order of the area this trail belongs to, if assigned, for sorting purposes.
 * @param images Images attached to this trail, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
 */
@Serializable

data class SummerTrail (

    /* Unique identifier for the trail. */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* Display name of the trail. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL-friendly name of the trail. */
    @SerialName(value = "slug")
    val slug: kotlin.String,

    /* Type of trail activity (e.g. hiking, mountain_biking). Can have multiple. */
    @SerialName(value = "trail_type")
    val trailType: kotlin.collections.List<@Contextual SummerTrailType>,

    /* Current operational status (open, closed, or unknown). */
    @Contextual @SerialName(value = "status")
    val status: SummerTrailStatus,

    /* Notes about current conditions on this trail. */
    @SerialName(value = "condition_notes")
    val conditionNotes: kotlin.String,

    /* When this trail's information was last updated. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Optional trail number. */
    @SerialName(value = "number")
    val number: kotlin.Int? = null,

    /* Difficulty rating of the trail (optional for summer trails). */
    @Contextual @SerialName(value = "difficulty")
    val difficulty: SummerTrailDifficulty? = null,

    /* UUID of the area this trail belongs to, if assigned. */
    @SerialName(value = "area_uuid")
    val areaUuid: kotlin.String? = null,

    /* Name of the area this trail belongs to, if assigned. */
    @SerialName(value = "area_name")
    val areaName: kotlin.String? = null,

    /* Display order of the area this trail belongs to, if assigned, for sorting purposes. */
    @SerialName(value = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null,

    /* Images attached to this trail, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    @SerialName(value = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (trailType.containsUnknownDefaultOpenApiCase()) return true
            if (status.containsUnknownDefaultOpenApiCase()) return true
            if (difficulty.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

