/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.SummerTrailDifficulty
import com.mtnmanager.sdk.models.SummerTrailStatus
import com.mtnmanager.sdk.models.SummerTrailType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a single summer trail at the resort with its current status,  type (e.g. hiking, mountain biking), and optional difficulty rating.
 *
 * @param uuid Unique identifier for the trail.
 * @param name Display name of the trail.
 * @param slug URL-friendly name of the trail.
 * @param trailType Type of trail activity (e.g. hiking, mountain_biking). Can have multiple.
 * @param status Current operational status (open, closed, or unknown).
 * @param conditionNotes Notes about current conditions on this trail.
 * @param updatedAt When this trail's information was last updated.
 * @param number Optional trail number.
 * @param difficulty Difficulty rating of the trail (optional for summer trails).
 * @param areaUuid UUID of the area this trail belongs to, if assigned.
 * @param areaName Name of the area this trail belongs to, if assigned.
 * @param areaDisplayOrder Display order of the area this trail belongs to, if assigned, for sorting purposes.
 * @param images Images attached to this trail, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
 */


data class SummerTrail (

    /* Unique identifier for the trail. */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* Display name of the trail. */
    @Json(name = "name")
    val name: kotlin.String,

    /* URL-friendly name of the trail. */
    @Json(name = "slug")
    val slug: kotlin.String,

    /* Type of trail activity (e.g. hiking, mountain_biking). Can have multiple. */
    @Json(name = "trail_type")
    val trailType: kotlin.collections.List<SummerTrailType>,

    /* Current operational status (open, closed, or unknown). */
    @Json(name = "status")
    val status: SummerTrailStatus,

    /* Notes about current conditions on this trail. */
    @Json(name = "condition_notes")
    val conditionNotes: kotlin.String,

    /* When this trail's information was last updated. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Optional trail number. */
    @Json(name = "number")
    val number: kotlin.Int? = null,

    /* Difficulty rating of the trail (optional for summer trails). */
    @Json(name = "difficulty")
    val difficulty: SummerTrailDifficulty? = null,

    /* UUID of the area this trail belongs to, if assigned. */
    @Json(name = "area_uuid")
    val areaUuid: kotlin.String? = null,

    /* Name of the area this trail belongs to, if assigned. */
    @Json(name = "area_name")
    val areaName: kotlin.String? = null,

    /* Display order of the area this trail belongs to, if assigned, for sorting purposes. */
    @Json(name = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null,

    /* Images attached to this trail, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    @Json(name = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) {


}

