/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * Industry-standard letter codes describing snow surface conditions.
 *
 * Values: BS,CO,FG,HP,IP,IS,LG,MG,P,PP,SC,TC,V,WG,WP,unknown_default_open_api
 */
@Serializable(with = SurfaceConditionSerializer::class)
enum class SurfaceCondition(val value: kotlin.String) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {

    @SerialName(value = "BS")
    BS("BS"),

    @SerialName(value = "CO")
    CO("CO"),

    @SerialName(value = "FG")
    FG("FG"),

    @SerialName(value = "HP")
    HP("HP"),

    @SerialName(value = "IP")
    IP("IP"),

    @SerialName(value = "IS")
    IS("IS"),

    @SerialName(value = "LG")
    LG("LG"),

    @SerialName(value = "MG")
    MG("MG"),

    @SerialName(value = "P")
    P("P"),

    @SerialName(value = "PP")
    PP("PP"),

    @SerialName(value = "SC")
    SC("SC"),

    @SerialName(value = "TC")
    TC("TC"),

    @SerialName(value = "V")
    V("V"),

    @SerialName(value = "WG")
    WG("WG"),

    @SerialName(value = "WP")
    WP("WP"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    /**
     * True when this value is the synthetic unknown default case that unknown
     * enum values are mapped to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() = this == unknown_default_open_api

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SurfaceCondition) "$data" else null

        /**
         * Returns a valid [SurfaceCondition] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SurfaceCondition? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object SurfaceConditionSerializer : KSerializer<SurfaceCondition> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): SurfaceCondition {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return SurfaceCondition.entries.firstOrNull { it.value == value }
            ?: SurfaceCondition.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: SurfaceCondition) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


