/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.FeatureSize
import com.mtnmanager.sdk.models.FeatureType
import com.mtnmanager.sdk.models.TerrainParkFeatureStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a single feature within a terrain park (jump, box, rail, etc.)  with its current status and size rating.
 *
 * @param uuid Unique identifier for the feature.
 * @param name Display name of the feature.
 * @param slug URL-friendly name of the run.
 * @param featureType Type of feature (jump, box, rail, other).
 * @param status Current operational status (open, closed, or unknown).  `unknown` unless the terrain park feature status is enabled.
 * @param number Optional feature number.
 * @param propertySize Optional size rating of the feature (S, M, L, XL).
 * @param images Images attached to this feature, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
 */


data class TerrainParkFeature (

    /* Unique identifier for the feature. */
    @Json(name = "uuid")
    val uuid: kotlin.String,

    /* Display name of the feature. */
    @Json(name = "name")
    val name: kotlin.String,

    /* URL-friendly name of the run. */
    @Json(name = "slug")
    val slug: kotlin.String,

    /* Type of feature (jump, box, rail, other). */
    @Json(name = "feature_type")
    val featureType: FeatureType,

    /* Current operational status (open, closed, or unknown).  `unknown` unless the terrain park feature status is enabled. */
    @Json(name = "status")
    val status: TerrainParkFeatureStatus,

    /* Optional feature number. */
    @Json(name = "number")
    val number: kotlin.Int? = null,

    /* Optional size rating of the feature (S, M, L, XL). */
    @Json(name = "size")
    val propertySize: FeatureSize? = null,

    /* Images attached to this feature, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    @Json(name = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) {


}

