/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.FeatureSize
import com.mtnmanager.sdk.models.FeatureType
import com.mtnmanager.sdk.models.TerrainParkFeatureStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * Represents a single feature within a terrain park (jump, box, rail, etc.)  with its current status and size rating.
 *
 * @param uuid Unique identifier for the feature.
 * @param name Display name of the feature.
 * @param slug URL-friendly name of the run.
 * @param featureType Type of feature (jump, box, rail, other).
 * @param status Current operational status (open, closed, or unknown).  `unknown` unless the terrain park feature status is enabled.
 * @param number Optional feature number.
 * @param propertySize Optional size rating of the feature (S, M, L, XL).
 * @param images Images attached to this feature, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
 */
@Serializable

data class TerrainParkFeature (

    /* Unique identifier for the feature. */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* Display name of the feature. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL-friendly name of the run. */
    @SerialName(value = "slug")
    val slug: kotlin.String,

    /* Type of feature (jump, box, rail, other). */
    @Contextual @SerialName(value = "feature_type")
    val featureType: FeatureType,

    /* Current operational status (open, closed, or unknown).  `unknown` unless the terrain park feature status is enabled. */
    @Contextual @SerialName(value = "status")
    val status: TerrainParkFeatureStatus,

    /* Optional feature number. */
    @SerialName(value = "number")
    val number: kotlin.Int? = null,

    /* Optional size rating of the feature (S, M, L, XL). */
    @Contextual @SerialName(value = "size")
    val propertySize: FeatureSize? = null,

    /* Images attached to this feature, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    @SerialName(value = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (featureType.containsUnknownDefaultOpenApiCase()) return true
            if (status.containsUnknownDefaultOpenApiCase()) return true
            if (propertySize.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

