/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.TerrainParkFeature
import com.mtnmanager.sdk.models.TerrainParkStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * Represents a terrain park at the resort with its current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within it.
 *
 * @param uuid Unique identifier for the terrain park.
 * @param name Display name of the terrain park.
 * @param slug URL-friendly name of the terrain park.
 * @param status Current operational status (open, closed, or unknown).
 * @param conditionNotes Notes about current conditions in this terrain park.
 * @param features Features within this terrain park (jumps, boxes, rails, etc.).
 * @param updatedAt When this terrain park or any of its features was last updated.
 * @param number Optional terrain park number.
 * @param areaUuid UUID of the area this terrain park belongs to, if assigned.
 * @param areaName Name of the area this terrain park belongs to, if assigned.
 * @param areaDisplayOrder Display order of the area this terrain park belongs to, if assigned, for sorting purposes.
 * @param images Images attached to this terrain park, ordered for display. Each includes  a ThumbHash for rendering a blurred placeholder while the image loads.
 */
@Serializable

data class TerrainPark (

    /* Unique identifier for the terrain park. */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* Display name of the terrain park. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL-friendly name of the terrain park. */
    @SerialName(value = "slug")
    val slug: kotlin.String,

    /* Current operational status (open, closed, or unknown). */
    @Contextual @SerialName(value = "status")
    val status: TerrainParkStatus,

    /* Notes about current conditions in this terrain park. */
    @SerialName(value = "condition_notes")
    val conditionNotes: kotlin.String,

    /* Features within this terrain park (jumps, boxes, rails, etc.). */
    @SerialName(value = "features")
    val features: kotlin.collections.List<TerrainParkFeature>,

    /* When this terrain park or any of its features was last updated. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Optional terrain park number. */
    @SerialName(value = "number")
    val number: kotlin.Int? = null,

    /* UUID of the area this terrain park belongs to, if assigned. */
    @SerialName(value = "area_uuid")
    val areaUuid: kotlin.String? = null,

    /* Name of the area this terrain park belongs to, if assigned. */
    @SerialName(value = "area_name")
    val areaName: kotlin.String? = null,

    /* Display order of the area this terrain park belongs to, if assigned, for sorting purposes. */
    @SerialName(value = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null,

    /* Images attached to this terrain park, ordered for display. Each includes  a ThumbHash for rendering a blurred placeholder while the image loads. */
    @SerialName(value = "images")
    val images: kotlin.collections.List<EntityImage>? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (status.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

