/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.MarkerIcon
import com.mtnmanager.sdk.models.Webcam

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param x 
 * @param y 
 * @param icon 
 * @param color 
 * @param webcam 
 * @param groupLabel 
 */
@Serializable

data class TrailMapElementOneOf6 (

    @SerialName(value = "type")
    val type: TrailMapElementOneOf6.Type,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "x")
    val x: kotlin.Double,

    @SerialName(value = "y")
    val y: kotlin.Double,

    @Contextual @SerialName(value = "icon")
    val icon: MarkerIcon? = null,

    @SerialName(value = "color")
    val color: kotlin.String? = null,

    @SerialName(value = "webcam")
    val webcam: Webcam? = null,

    @SerialName(value = "group_label")
    val groupLabel: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: webcam_marker
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "webcam_marker") webcam_marker("webcam_marker");
    }

}

