/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.Amenity
import com.mtnmanager.sdk.models.LabelOffset
import com.mtnmanager.sdk.models.Lift
import com.mtnmanager.sdk.models.MarkerIcon
import com.mtnmanager.sdk.models.ParkingLot
import com.mtnmanager.sdk.models.Run
import com.mtnmanager.sdk.models.SummerTrail
import com.mtnmanager.sdk.models.TerrainPark
import com.mtnmanager.sdk.models.TrailMapElementOneOf
import com.mtnmanager.sdk.models.TrailMapElementOneOf1
import com.mtnmanager.sdk.models.TrailMapElementOneOf2
import com.mtnmanager.sdk.models.TrailMapElementOneOf3
import com.mtnmanager.sdk.models.TrailMapElementOneOf4
import com.mtnmanager.sdk.models.TrailMapElementOneOf5
import com.mtnmanager.sdk.models.TrailMapElementOneOf6
import com.mtnmanager.sdk.models.TrailMapElementOneOf7
import com.mtnmanager.sdk.models.Webcam

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.encodeToJsonElement

/**
 * A trail map element with full entity data from existing public models.
 *
 */
@Serializable(with = TrailMapElementSerializer::class)
sealed interface TrailMapElement {
    @JvmInline
    value class TrailMapElementOneOfValue(val value: TrailMapElementOneOf) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf1Value(val value: TrailMapElementOneOf1) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf2Value(val value: TrailMapElementOneOf2) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf3Value(val value: TrailMapElementOneOf3) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf4Value(val value: TrailMapElementOneOf4) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf5Value(val value: TrailMapElementOneOf5) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf6Value(val value: TrailMapElementOneOf6) : TrailMapElement

    @JvmInline
    value class TrailMapElementOneOf7Value(val value: TrailMapElementOneOf7) : TrailMapElement

}

object TrailMapElementSerializer : KSerializer<TrailMapElement> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("TrailMapElement")

    override fun serialize(encoder: Encoder, value: TrailMapElement) {
        val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("TrailMapElement can only be serialized with Json")

        when (value) {
            is TrailMapElement.TrailMapElementOneOfValue -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf1Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf1.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf2Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf2.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf3Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf3.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf4Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf4.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf5Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf5.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf6Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf6.serializer(), value.value)
            is TrailMapElement.TrailMapElementOneOf7Value -> jsonEncoder.encodeSerializableValue(TrailMapElementOneOf7.serializer(), value.value)
        }
    }

    override fun deserialize(decoder: Decoder): TrailMapElement {
        val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("TrailMapElement can only be deserialized with Json")
        val jsonElement = jsonDecoder.decodeJsonElement()

        val errorMessages = mutableListOf<String>()

        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf>(jsonElement)
                return TrailMapElement.TrailMapElementOneOfValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf1>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf1Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf1: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf2>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf2Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf2: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf3>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf3Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf3: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf4>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf4Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf4: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf5>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf5Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf5: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf6>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf6Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf6: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TrailMapElementOneOf7>(jsonElement)
                return TrailMapElement.TrailMapElementOneOf7Value(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TrailMapElementOneOf7: ${e.message}")
            }
        }

        throw SerializationException("Cannot deserialize TrailMapElement. Tried: ${errorMessages.joinToString(", ")}")
    }
}

