/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.LabelOffset
import com.mtnmanager.sdk.models.TerrainPark

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param points 
 * @param tension 
 * @param labelOffset 
 * @param terrainPark 
 */


data class TrailMapElementOneOf2 (

    @Json(name = "type")
    val type: TrailMapElementOneOf2.Type,

    @Json(name = "uuid")
    val uuid: kotlin.String,

    @Json(name = "points")
    val points: kotlin.collections.List<kotlin.Double>,

    @Json(name = "tension")
    val tension: kotlin.Double? = null,

    @Json(name = "label_offset")
    val labelOffset: LabelOffset? = null,

    @Json(name = "terrain_park")
    val terrainPark: TerrainPark? = null

) {

    /**
     * 
     *
     * Values: terrain_park
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "terrain_park") terrain_park("terrain_park");
    }

}

