/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.GeoControlPoint
import com.mtnmanager.sdk.models.ResortInfo
import com.mtnmanager.sdk.models.SeasonType
import com.mtnmanager.sdk.models.TrailMapElement

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * A public trail map with enriched entity data.
 *
 * @param uuid 
 * @param name 
 * @param slug 
 * @param season 
 * @param displayOrder 
 * @param version Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map.
 * @param backgroundImageUrl 
 * @param resort 
 * @param elements 
 * @param geoControlPoints 
 */
@Serializable

data class TrailMap (

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @Contextual @SerialName(value = "season")
    val season: SeasonType,

    @SerialName(value = "display_order")
    val displayOrder: kotlin.Long,

    /* Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map. */
    @SerialName(value = "version")
    val version: kotlin.Long,

    @SerialName(value = "background_image_url")
    val backgroundImageUrl: kotlin.String,

    @SerialName(value = "resort")
    val resort: ResortInfo,

    @SerialName(value = "elements")
    val elements: kotlin.collections.List<TrailMapElement>,

    @SerialName(value = "geo_control_points")
    val geoControlPoints: kotlin.collections.List<GeoControlPoint>? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (season.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

