/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.MarkerIcon

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param x 
 * @param y 
 * @param parkingLotUuid 
 * @param icon 
 * @param color 
 * @param groupLabel 
 */
@Serializable

data class TrailMapStaticElementOneOf5 (

    @SerialName(value = "type")
    val type: TrailMapStaticElementOneOf5.Type,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "x")
    val x: kotlin.Double,

    @SerialName(value = "y")
    val y: kotlin.Double,

    @SerialName(value = "parking_lot_uuid")
    val parkingLotUuid: kotlin.String,

    @Contextual @SerialName(value = "icon")
    val icon: MarkerIcon? = null,

    @SerialName(value = "color")
    val color: kotlin.String? = null,

    @SerialName(value = "group_label")
    val groupLabel: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: parking_lot_marker,unknown_default_open_api
     */
    @Serializable(with = TypeSerializer::class)
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "parking_lot_marker") parking_lot_marker("parking_lot_marker"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object TypeSerializer : KSerializer<Type> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Type {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Type.entries.firstOrNull { it.value == value }
                ?: Type.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Type) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

