/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.MarkerIcon
import com.mtnmanager.sdk.models.ParkingLot

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param x 
 * @param y 
 * @param icon 
 * @param color 
 * @param parkingLot 
 * @param groupLabel 
 */


data class TrailMapElementOneOf5 (

    @Json(name = "type")
    val type: TrailMapElementOneOf5.Type,

    @Json(name = "uuid")
    val uuid: kotlin.String,

    @Json(name = "x")
    val x: kotlin.Double,

    @Json(name = "y")
    val y: kotlin.Double,

    @Json(name = "icon")
    val icon: MarkerIcon? = null,

    @Json(name = "color")
    val color: kotlin.String? = null,

    @Json(name = "parking_lot")
    val parkingLot: ParkingLot? = null,

    @Json(name = "group_label")
    val groupLabel: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: parking_lot_marker
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "parking_lot_marker") parking_lot_marker("parking_lot_marker");
    }

}

