/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.Run

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param points 
 * @param tension 
 * @param run 
 */
@Serializable

data class TrailMapElementOneOf1 (

    @SerialName(value = "type")
    val type: TrailMapElementOneOf1.Type,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "points")
    val points: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "tension")
    val tension: kotlin.Double? = null,

    @SerialName(value = "run")
    val run: Run? = null

) {

    /**
     * 
     *
     * Values: run
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "run") run("run");
    }

}

