/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.GeoBounds
import com.mtnmanager.sdk.models.SeasonType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * Summary metadata for a trail map.
 *
 * @param uuid 
 * @param name 
 * @param season 
 * @param displayOrder 
 * @param version Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map.
 * @param hostedUrl 
 * @param entityUuids Deduplicated UUIDs of every entity (lift, run, terrain park,  summer trail, amenity, parking lot) referenced by this map's elements.
 * @param geoBounds Lat/lng bounding box of this map's georeferenced area, plus the  centroid of its control points (used for tie-breaking when multiple  maps cover the same point). Omitted when the map has no georeferencing.
 */
@Serializable

data class TrailMapSummary (

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "season")
    val season: SeasonType,

    @SerialName(value = "display_order")
    val displayOrder: kotlin.Long,

    /* Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map. */
    @SerialName(value = "version")
    val version: kotlin.Long,

    @SerialName(value = "hosted_url")
    val hostedUrl: kotlin.String,

    /* Deduplicated UUIDs of every entity (lift, run, terrain park,  summer trail, amenity, parking lot) referenced by this map's elements. */
    @SerialName(value = "entity_uuids")
    val entityUuids: kotlin.collections.List<kotlin.String>,

    /* Lat/lng bounding box of this map's georeferenced area, plus the  centroid of its control points (used for tie-breaking when multiple  maps cover the same point). Omitted when the map has no georeferencing. */
    @SerialName(value = "geo_bounds")
    val geoBounds: GeoBounds? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {


    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (season.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

