/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.SummerTrail

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import com.mtnmanager.sdk.infrastructure.containsUnknownDefaultOpenApiCase

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param points 
 * @param tension 
 * @param summerTrail 
 */
@Serializable

data class TrailMapElementOneOf3 (

    @SerialName(value = "type")
    val type: TrailMapElementOneOf3.Type,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "points")
    val points: kotlin.collections.List<kotlin.Double>,

    @SerialName(value = "tension")
    val tension: kotlin.Double? = null,

    @SerialName(value = "summer_trail")
    val summerTrail: SummerTrail? = null

) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {

    /**
     * 
     *
     * Values: summer_trail,unknown_default_open_api
     */
    @Serializable(with = TypeSerializer::class)
    enum class Type(val value: kotlin.String) : com.mtnmanager.sdk.infrastructure.UnknownCaseCheckable {
        @SerialName(value = "summer_trail") summer_trail("summer_trail"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");

        /**
         * True when this value is the synthetic unknown default case that unknown
         * enum values are mapped to during deserialization.
         */
        override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
            get() = this == unknown_default_open_api
    }

    internal object TypeSerializer : KSerializer<Type> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Type {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Type.entries.firstOrNull { it.value == value }
                ?: Type.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Type) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

    /**
     * True when any enum property (or enum item of an array property) of this model
     * holds the synthetic unknown default case that unknown enum values are mapped
     * to during deserialization.
     */
    override val containsUnknownDefaultOpenApiCase: kotlin.Boolean
        get() {
            if (type.containsUnknownDefaultOpenApiCase()) return true
            return false
        }

}

