/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.GeoControlPoint
import com.mtnmanager.sdk.models.ResortInfo
import com.mtnmanager.sdk.models.SeasonType
import com.mtnmanager.sdk.models.TrailMapElement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A public trail map with enriched entity data.
 *
 * @param uuid 
 * @param name 
 * @param slug 
 * @param season 
 * @param displayOrder 
 * @param version Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map.
 * @param backgroundImageUrl 
 * @param resort 
 * @param elements 
 * @param geoControlPoints 
 */


data class TrailMap (

    @Json(name = "uuid")
    val uuid: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "slug")
    val slug: kotlin.String,

    @Json(name = "season")
    val season: SeasonType,

    @Json(name = "display_order")
    val displayOrder: kotlin.Long,

    /* Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map. */
    @Json(name = "version")
    val version: kotlin.Long,

    @Json(name = "background_image_url")
    val backgroundImageUrl: kotlin.String,

    @Json(name = "resort")
    val resort: ResortInfo,

    @Json(name = "elements")
    val elements: kotlin.collections.List<TrailMapElement>,

    @Json(name = "geo_control_points")
    val geoControlPoints: kotlin.collections.List<GeoControlPoint>? = null

) {


}

