/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.SummerTrail

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param uuid 
 * @param points 
 * @param tension 
 * @param summerTrail 
 */


data class TrailMapElementOneOf3 (

    @Json(name = "type")
    val type: TrailMapElementOneOf3.Type,

    @Json(name = "uuid")
    val uuid: kotlin.String,

    @Json(name = "points")
    val points: kotlin.collections.List<kotlin.Double>,

    @Json(name = "tension")
    val tension: kotlin.Double? = null,

    @Json(name = "summer_trail")
    val summerTrail: SummerTrail? = null

) {

    /**
     * 
     *
     * Values: summer_trail
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "summer_trail") summer_trail("summer_trail");
    }

}

