/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Path params for the versioned static endpoint: the map's UUID plus the  specific `version` the client is asking for. The version lives in the URL so  each version is an immutable resource (see `get_trail_map_static`).
 *
 * @param uuid Trail map UUID
 * @param version The map version being requested (from `TrailMapSummary.version`)
 */
@Serializable

data class TrailMapStaticPath (

    /* Trail map UUID */
    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    /* The map version being requested (from `TrailMapSummary.version`) */
    @SerialName(value = "version")
    val version: kotlin.Long

) {


}

