/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * Weather condition code
 *
 * Values: Clear,Cloudy,Foggy,Haze,MostlyClear,MostlyCloudy,PartlyCloudy,Smoky,BlowingDust,Breezy,Windy,Drizzle,HeavyRain,IsolatedThunderstorms,Rain,SunShowers,ScatteredThunderstorms,StrongStorms,Thunderstorms,Frigid,Hail,Hot,Flurries,Sleet,Snow,SunFlurries,WintryMix,Blizzard,BlowingSnow,FreezingDrizzle,FreezingRain,HeavySnow,Hurricane,TropicalStorm,Unknown,unknown_default_open_api
 */
@Serializable(with = WeatherConditionCodeSerializer::class)
enum class WeatherConditionCode(val value: kotlin.String) {

    @SerialName(value = "Clear")
    Clear("Clear"),

    @SerialName(value = "Cloudy")
    Cloudy("Cloudy"),

    @SerialName(value = "Foggy")
    Foggy("Foggy"),

    @SerialName(value = "Haze")
    Haze("Haze"),

    @SerialName(value = "MostlyClear")
    MostlyClear("MostlyClear"),

    @SerialName(value = "MostlyCloudy")
    MostlyCloudy("MostlyCloudy"),

    @SerialName(value = "PartlyCloudy")
    PartlyCloudy("PartlyCloudy"),

    @SerialName(value = "Smoky")
    Smoky("Smoky"),

    @SerialName(value = "BlowingDust")
    BlowingDust("BlowingDust"),

    @SerialName(value = "Breezy")
    Breezy("Breezy"),

    @SerialName(value = "Windy")
    Windy("Windy"),

    @SerialName(value = "Drizzle")
    Drizzle("Drizzle"),

    @SerialName(value = "HeavyRain")
    HeavyRain("HeavyRain"),

    @SerialName(value = "IsolatedThunderstorms")
    IsolatedThunderstorms("IsolatedThunderstorms"),

    @SerialName(value = "Rain")
    Rain("Rain"),

    @SerialName(value = "SunShowers")
    SunShowers("SunShowers"),

    @SerialName(value = "ScatteredThunderstorms")
    ScatteredThunderstorms("ScatteredThunderstorms"),

    @SerialName(value = "StrongStorms")
    StrongStorms("StrongStorms"),

    @SerialName(value = "Thunderstorms")
    Thunderstorms("Thunderstorms"),

    @SerialName(value = "Frigid")
    Frigid("Frigid"),

    @SerialName(value = "Hail")
    Hail("Hail"),

    @SerialName(value = "Hot")
    Hot("Hot"),

    @SerialName(value = "Flurries")
    Flurries("Flurries"),

    @SerialName(value = "Sleet")
    Sleet("Sleet"),

    @SerialName(value = "Snow")
    Snow("Snow"),

    @SerialName(value = "SunFlurries")
    SunFlurries("SunFlurries"),

    @SerialName(value = "WintryMix")
    WintryMix("WintryMix"),

    @SerialName(value = "Blizzard")
    Blizzard("Blizzard"),

    @SerialName(value = "BlowingSnow")
    BlowingSnow("BlowingSnow"),

    @SerialName(value = "FreezingDrizzle")
    FreezingDrizzle("FreezingDrizzle"),

    @SerialName(value = "FreezingRain")
    FreezingRain("FreezingRain"),

    @SerialName(value = "HeavySnow")
    HeavySnow("HeavySnow"),

    @SerialName(value = "Hurricane")
    Hurricane("Hurricane"),

    @SerialName(value = "TropicalStorm")
    TropicalStorm("TropicalStorm"),

    @SerialName(value = "Unknown")
    Unknown("Unknown"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WeatherConditionCode) "$data" else null

        /**
         * Returns a valid [WeatherConditionCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WeatherConditionCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object WeatherConditionCodeSerializer : KSerializer<WeatherConditionCode> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): WeatherConditionCode {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return WeatherConditionCode.entries.firstOrNull { it.value == value }
            ?: WeatherConditionCode.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: WeatherConditionCode) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


