/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Weather condition code
 *
 * Values: Clear,Cloudy,Foggy,Haze,MostlyClear,MostlyCloudy,PartlyCloudy,Smoky,BlowingDust,Breezy,Windy,Drizzle,HeavyRain,IsolatedThunderstorms,Rain,SunShowers,ScatteredThunderstorms,StrongStorms,Thunderstorms,Frigid,Hail,Hot,Flurries,Sleet,Snow,SunFlurries,WintryMix,Blizzard,BlowingSnow,FreezingDrizzle,FreezingRain,HeavySnow,Hurricane,TropicalStorm,Unknown
 */

@JsonClass(generateAdapter = false)
enum class WeatherConditionCode(val value: kotlin.String) {

    @Json(name = "Clear")
    Clear("Clear"),

    @Json(name = "Cloudy")
    Cloudy("Cloudy"),

    @Json(name = "Foggy")
    Foggy("Foggy"),

    @Json(name = "Haze")
    Haze("Haze"),

    @Json(name = "MostlyClear")
    MostlyClear("MostlyClear"),

    @Json(name = "MostlyCloudy")
    MostlyCloudy("MostlyCloudy"),

    @Json(name = "PartlyCloudy")
    PartlyCloudy("PartlyCloudy"),

    @Json(name = "Smoky")
    Smoky("Smoky"),

    @Json(name = "BlowingDust")
    BlowingDust("BlowingDust"),

    @Json(name = "Breezy")
    Breezy("Breezy"),

    @Json(name = "Windy")
    Windy("Windy"),

    @Json(name = "Drizzle")
    Drizzle("Drizzle"),

    @Json(name = "HeavyRain")
    HeavyRain("HeavyRain"),

    @Json(name = "IsolatedThunderstorms")
    IsolatedThunderstorms("IsolatedThunderstorms"),

    @Json(name = "Rain")
    Rain("Rain"),

    @Json(name = "SunShowers")
    SunShowers("SunShowers"),

    @Json(name = "ScatteredThunderstorms")
    ScatteredThunderstorms("ScatteredThunderstorms"),

    @Json(name = "StrongStorms")
    StrongStorms("StrongStorms"),

    @Json(name = "Thunderstorms")
    Thunderstorms("Thunderstorms"),

    @Json(name = "Frigid")
    Frigid("Frigid"),

    @Json(name = "Hail")
    Hail("Hail"),

    @Json(name = "Hot")
    Hot("Hot"),

    @Json(name = "Flurries")
    Flurries("Flurries"),

    @Json(name = "Sleet")
    Sleet("Sleet"),

    @Json(name = "Snow")
    Snow("Snow"),

    @Json(name = "SunFlurries")
    SunFlurries("SunFlurries"),

    @Json(name = "WintryMix")
    WintryMix("WintryMix"),

    @Json(name = "Blizzard")
    Blizzard("Blizzard"),

    @Json(name = "BlowingSnow")
    BlowingSnow("BlowingSnow"),

    @Json(name = "FreezingDrizzle")
    FreezingDrizzle("FreezingDrizzle"),

    @Json(name = "FreezingRain")
    FreezingRain("FreezingRain"),

    @Json(name = "HeavySnow")
    HeavySnow("HeavySnow"),

    @Json(name = "Hurricane")
    Hurricane("Hurricane"),

    @Json(name = "TropicalStorm")
    TropicalStorm("TropicalStorm"),

    @Json(name = "Unknown")
    Unknown("Unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WeatherConditionCode) "$data" else null

        /**
         * Returns a valid [WeatherConditionCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WeatherConditionCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

