/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import com.mtnmanager.sdk.models.CurrentWeather
import com.mtnmanager.sdk.models.DailyForecast
import com.mtnmanager.sdk.models.HourlyForecast

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Current and forecasted weather conditions for the resort's location.  Only included/available if the weather feature is enabled and GPS coordinates are configured.
 *
 * @param current Current weather conditions
 * @param hourlyForecast Hourly forecast for next 24 hours (including current hour)
 * @param dailyForecast Daily forecast for next 7 days (including today)
 * @param attribution Data source attribution
 * @param updatedAt When this data was last updated
 * @param areaUuid The area this weather belongs to, or omitted for resort-wide weather.
 * @param areaName The area's name, or omitted for resort-wide weather.
 * @param areaDisplayOrder The area's display order, or omitted for resort-wide weather.
 */


data class Weather (

    /* Current weather conditions */
    @Json(name = "current")
    val current: CurrentWeather,

    /* Hourly forecast for next 24 hours (including current hour) */
    @Json(name = "hourly_forecast")
    val hourlyForecast: kotlin.collections.List<HourlyForecast>,

    /* Daily forecast for next 7 days (including today) */
    @Json(name = "daily_forecast")
    val dailyForecast: kotlin.collections.List<DailyForecast>,

    /* Data source attribution */
    @Json(name = "attribution")
    val attribution: kotlin.String,

    /* When this data was last updated */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* The area this weather belongs to, or omitted for resort-wide weather. */
    @Json(name = "area_uuid")
    val areaUuid: kotlin.String? = null,

    /* The area's name, or omitted for resort-wide weather. */
    @Json(name = "area_name")
    val areaName: kotlin.String? = null,

    /* The area's display order, or omitted for resort-wide weather. */
    @Json(name = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null

) {


}

