/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Query parameters for the history endpoint.
 *
 * @param from Inclusive lower bound on `captured_at` (RFC 3339).
 * @param to Inclusive upper bound on `captured_at` (RFC 3339).
 */
@Serializable

data class WebcamHistoryQuery (

    /* Inclusive lower bound on `captured_at` (RFC 3339). */
    @SerialName(value = "from")
    val from: kotlin.String? = null,

    /* Inclusive upper bound on `captured_at` (RFC 3339). */
    @SerialName(value = "to")
    val to: kotlin.String? = null

) {


}

