/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A single archived historical frame.
 *
 * @param capturedAt 
 * @param imageUrl 
 * @param thumbUrl 
 * @param thumbhash ThumbHash of the frame (standard base64), recovered from the thumb object's  key. Empty string for legacy frames archived without one.
 */


data class WebcamHistoryFrame (

    @Json(name = "captured_at")
    val capturedAt: kotlin.String,

    @Json(name = "image_url")
    val imageUrl: kotlin.String,

    @Json(name = "thumb_url")
    val thumbUrl: kotlin.String,

    /* ThumbHash of the frame (standard base64), recovered from the thumb object's  key. Empty string for legacy frames archived without one. */
    @Json(name = "thumbhash")
    val thumbhash: kotlin.String

) {


}

