/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * A public webcam entry. Consumers pick `latest` (always the newest frame) or  `latest-daylight` (the last daylight frame, never a black night shot)  depending on whether they want the freshest or a guaranteed-lit image.
 *
 * @param uuid 
 * @param name 
 * @param latestImageUrl URL of the newest frame (refreshes within ~60s via the edge cache).
 * @param latestDaylightImageUrl URL of the last daylight frame.
 * @param latestThumbUrl 
 * @param latestDaylightThumbUrl 
 * @param latestThumbhash ThumbHash of the `latest` frame (standard base64) — a compact blur  placeholder to render while the image loads. Empty string until the first  frame (or on cameras predating the feature).
 * @param latestDaylightThumbhash ThumbHash of the `latest-daylight` frame (standard base64). Empty string  until the first daylight frame.
 * @param hasHistory Whether this camera archives frames — i.e. whether its history endpoint  returns anything. When `false`, don't call the history API for it.
 * @param areaUuid 
 * @param areaName 
 * @param areaDisplayOrder 
 * @param elevationFt Camera elevation in both units; omitted when unset.
 * @param elevationM 
 * @param lastFrameAt Time of the most recently published frame; omitted until the first frame.
 */
@Serializable

data class Webcam (

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* URL of the newest frame (refreshes within ~60s via the edge cache). */
    @SerialName(value = "latest_image_url")
    val latestImageUrl: kotlin.String,

    /* URL of the last daylight frame. */
    @SerialName(value = "latest_daylight_image_url")
    val latestDaylightImageUrl: kotlin.String,

    @SerialName(value = "latest_thumb_url")
    val latestThumbUrl: kotlin.String,

    @SerialName(value = "latest_daylight_thumb_url")
    val latestDaylightThumbUrl: kotlin.String,

    /* ThumbHash of the `latest` frame (standard base64) — a compact blur  placeholder to render while the image loads. Empty string until the first  frame (or on cameras predating the feature). */
    @SerialName(value = "latest_thumbhash")
    val latestThumbhash: kotlin.String,

    /* ThumbHash of the `latest-daylight` frame (standard base64). Empty string  until the first daylight frame. */
    @SerialName(value = "latest_daylight_thumbhash")
    val latestDaylightThumbhash: kotlin.String,

    /* Whether this camera archives frames — i.e. whether its history endpoint  returns anything. When `false`, don't call the history API for it. */
    @SerialName(value = "has_history")
    val hasHistory: kotlin.Boolean,

    @SerialName(value = "area_uuid")
    val areaUuid: kotlin.String? = null,

    @SerialName(value = "area_name")
    val areaName: kotlin.String? = null,

    @SerialName(value = "area_display_order")
    val areaDisplayOrder: kotlin.Int? = null,

    /* Camera elevation in both units; omitted when unset. */
    @SerialName(value = "elevation_ft")
    val elevationFt: kotlin.Int? = null,

    @SerialName(value = "elevation_m")
    val elevationM: kotlin.Int? = null,

    /* Time of the most recently published frame; omitted until the first frame. */
    @SerialName(value = "last_frame_at")
    val lastFrameAt: kotlin.String? = null

) {


}

