/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.Amenity
import com.mtnmanager.sdk.models.AmenityCategory
import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.Schedule

class AmenityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Amenity
        //val modelInstance = Amenity()

        // to test the property `description` - Description of the amenity.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `uuid` - Unique identifier for the amenity.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name` - Display name of the amenity.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `category` - Category classification (e.g. restaurant, lodge, ski_school).
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `website` - Website URL for the amenity, if available.
        should("test website") {
            // uncomment below to test the property
            //modelInstance.website shouldBe ("TODO")
        }

        // to test the property `hasOperatingHours` - Whether this amenity reports operating hours. When false, clients should  not expect `opens_at`, `closes_at`, or `schedules` to ever be populated.
        should("test hasOperatingHours") {
            // uncomment below to test the property
            //modelInstance.hasOperatingHours shouldBe ("TODO")
        }

        // to test the property `schedules` - Recurring operating schedules for this amenity (e.g. \"Saturday & Sunday,  9:00 a.m. to 4:00 p.m.\"), with both human-readable and structured fields.
        should("test schedules") {
            // uncomment below to test the property
            //modelInstance.schedules shouldBe ("TODO")
        }

        // to test the property `opensAt` - Today's scheduled opening time in 24-hour format (HH:MM), in resort's local timezone.
        should("test opensAt") {
            // uncomment below to test the property
            //modelInstance.opensAt shouldBe ("TODO")
        }

        // to test the property `closesAt` - Today's scheduled closing time in 24-hour format (HH:MM), in resort's local timezone.
        should("test closesAt") {
            // uncomment below to test the property
            //modelInstance.closesAt shouldBe ("TODO")
        }

        // to test the property `images` - Images attached to this amenity, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

    }
}
