/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.CalendarDay
import com.mtnmanager.sdk.models.AmenityCalendarEntry
import com.mtnmanager.sdk.models.ClosureReason
import com.mtnmanager.sdk.models.DayOfWeek

class CalendarDayTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalendarDay
        //val modelInstance = CalendarDay()

        // to test the property `date` - Calendar date (YYYY-MM-DD).
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `dayOfWeek` - Day of the week.
        should("test dayOfWeek") {
            // uncomment below to test the property
            //modelInstance.dayOfWeek shouldBe ("TODO")
        }

        // to test the property `isOpen` - Whether the resort is open on this day.
        should("test isOpen") {
            // uncomment below to test the property
            //modelInstance.isOpen shouldBe ("TODO")
        }

        // to test the property `opensAt` - Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
        should("test opensAt") {
            // uncomment below to test the property
            //modelInstance.opensAt shouldBe ("TODO")
        }

        // to test the property `closesAt` - Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
        should("test closesAt") {
            // uncomment below to test the property
            //modelInstance.closesAt shouldBe ("TODO")
        }

        // to test the property `closureReason` - Optional reason code for closure.
        should("test closureReason") {
            // uncomment below to test the property
            //modelInstance.closureReason shouldBe ("TODO")
        }

        // to test the property `specialEvent` - Special event for this day.
        should("test specialEvent") {
            // uncomment below to test the property
            //modelInstance.specialEvent shouldBe ("TODO")
        }

        // to test the property `amenities` - Per-amenity hours for this day. Only included when amenity hours are configured.
        should("test amenities") {
            // uncomment below to test the property
            //modelInstance.amenities shouldBe ("TODO")
        }

    }
}
