/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.DailyForecast
import com.mtnmanager.sdk.models.DailyForecastImperial
import com.mtnmanager.sdk.models.DailyForecastMetric
import com.mtnmanager.sdk.models.WeatherConditionCode

class DailyForecastTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DailyForecast
        //val modelInstance = DailyForecast()

        // to test the property `date` - Date of forecast (YYYY-MM-DD format)
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `imperial` - Measurements in imperial units
        should("test imperial") {
            // uncomment below to test the property
            //modelInstance.imperial shouldBe ("TODO")
        }

        // to test the property `metric` - Measurements in metric units
        should("test metric") {
            // uncomment below to test the property
            //modelInstance.metric shouldBe ("TODO")
        }

        // to test the property `condition` - Human-readable condition
        should("test condition") {
            // uncomment below to test the property
            //modelInstance.condition shouldBe ("TODO")
        }

        // to test the property `conditionCode` - Condition code
        should("test conditionCode") {
            // uncomment below to test the property
            //modelInstance.conditionCode shouldBe ("TODO")
        }

        // to test the property `sunrise` - Sunrise time
        should("test sunrise") {
            // uncomment below to test the property
            //modelInstance.sunrise shouldBe ("TODO")
        }

        // to test the property `sunset` - Sunset time
        should("test sunset") {
            // uncomment below to test the property
            //modelInstance.sunset shouldBe ("TODO")
        }

        // to test the property `precipitationProbability` - Probability of precipitation (0-100%)
        should("test precipitationProbability") {
            // uncomment below to test the property
            //modelInstance.precipitationProbability shouldBe ("TODO")
        }

    }
}
