/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.DailyForecastMetric

class DailyForecastMetricTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DailyForecastMetric
        //val modelInstance = DailyForecastMetric()

        // to test the property `temperatureHigh` - High temperature in Celsius
        should("test temperatureHigh") {
            // uncomment below to test the property
            //modelInstance.temperatureHigh shouldBe ("TODO")
        }

        // to test the property `temperatureLow` - Low temperature in Celsius
        should("test temperatureLow") {
            // uncomment below to test the property
            //modelInstance.temperatureLow shouldBe ("TODO")
        }

        // to test the property `snowfallTotal` - Total snowfall expected in centimeters
        should("test snowfallTotal") {
            // uncomment below to test the property
            //modelInstance.snowfallTotal shouldBe ("TODO")
        }

        // to test the property `precipitationTotal` - Total precipitation expected in millimeters
        should("test precipitationTotal") {
            // uncomment below to test the property
            //modelInstance.precipitationTotal shouldBe ("TODO")
        }

        // to test the property `windSpeedMax` - Maximum wind speed in km/h
        should("test windSpeedMax") {
            // uncomment below to test the property
            //modelInstance.windSpeedMax shouldBe ("TODO")
        }

        // to test the property `windGustMax` - Maximum wind gust in km/h
        should("test windGustMax") {
            // uncomment below to test the property
            //modelInstance.windGustMax shouldBe ("TODO")
        }

    }
}
