/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.FullReport
import com.mtnmanager.sdk.models.Lift
import com.mtnmanager.sdk.models.OperatingHours
import com.mtnmanager.sdk.models.Overview
import com.mtnmanager.sdk.models.ParkingLot
import com.mtnmanager.sdk.models.ResortInfo
import com.mtnmanager.sdk.models.Run
import com.mtnmanager.sdk.models.SnowReport
import com.mtnmanager.sdk.models.SummerTrail
import com.mtnmanager.sdk.models.TerrainPark
import com.mtnmanager.sdk.models.Weather
import com.mtnmanager.sdk.models.Webcam

class FullReportTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FullReport
        //val modelInstance = FullReport()

        // to test the property `resort`
        should("test resort") {
            // uncomment below to test the property
            //modelInstance.resort shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `snow` - Provides current snow conditions including base depth, surface conditions,  and snowfall totals in both metric and imperial units.   May contain multiple, representing different reporting areas.
        should("test snow") {
            // uncomment below to test the property
            //modelInstance.snow shouldBe ("TODO")
        }

        // to test the property `lifts` - List of all lifts at the resort with their current operational status,  type, and optional wait time information.
        should("test lifts") {
            // uncomment below to test the property
            //modelInstance.lifts shouldBe ("TODO")
        }

        // to test the property `runs` - List of all runs at the resort with their current status,  grooming information, and difficulty rating.
        should("test runs") {
            // uncomment below to test the property
            //modelInstance.runs shouldBe ("TODO")
        }

        // to test the property `terrainParks` - List of all terrain parks at the resort with their current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within them.
        should("test terrainParks") {
            // uncomment below to test the property
            //modelInstance.terrainParks shouldBe ("TODO")
        }

        // to test the property `parkingLots` - List of all parking lots at the resort with their current status and amenities.
        should("test parkingLots") {
            // uncomment below to test the property
            //modelInstance.parkingLots shouldBe ("TODO")
        }

        // to test the property `summerTrails` - List of all summer trails at the resort with their current status,  type (e.g. hiking, mountain biking), and optional difficulty rating.
        should("test summerTrails") {
            // uncomment below to test the property
            //modelInstance.summerTrails shouldBe ("TODO")
        }

        // to test the property `hours`
        should("test hours") {
            // uncomment below to test the property
            //modelInstance.hours shouldBe ("TODO")
        }

        // to test the property `weather` - Weather entries: the resort-wide entry first (current + forecast), then  any per-area current-conditions entries. Empty when weather is disabled  or unavailable.
        should("test weather") {
            // uncomment below to test the property
            //modelInstance.weather shouldBe ("TODO")
        }

        // to test the property `webcams` - Enabled webcams with the URLs of their current and last-daylight frames  plus thumbnails. Empty when the resort does not have webcams.
        should("test webcams") {
            // uncomment below to test the property
            //modelInstance.webcams shouldBe ("TODO")
        }

    }
}
