/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.GeoBounds
import com.mtnmanager.sdk.models.GeoPoint

class GeoBoundsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GeoBounds
        //val modelInstance = GeoBounds()

        // to test the property `minLat`
        should("test minLat") {
            // uncomment below to test the property
            //modelInstance.minLat shouldBe ("TODO")
        }

        // to test the property `maxLat`
        should("test maxLat") {
            // uncomment below to test the property
            //modelInstance.maxLat shouldBe ("TODO")
        }

        // to test the property `minLng`
        should("test minLng") {
            // uncomment below to test the property
            //modelInstance.minLng shouldBe ("TODO")
        }

        // to test the property `maxLng`
        should("test maxLng") {
            // uncomment below to test the property
            //modelInstance.maxLng shouldBe ("TODO")
        }

        // to test the property `center`
        should("test center") {
            // uncomment below to test the property
            //modelInstance.center shouldBe ("TODO")
        }

    }
}
