/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.GeoControlPoint

class GeoControlPointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GeoControlPoint
        //val modelInstance = GeoControlPoint()

        // to test the property `pixelX`
        should("test pixelX") {
            // uncomment below to test the property
            //modelInstance.pixelX shouldBe ("TODO")
        }

        // to test the property `pixelY`
        should("test pixelY") {
            // uncomment below to test the property
            //modelInstance.pixelY shouldBe ("TODO")
        }

        // to test the property `lat`
        should("test lat") {
            // uncomment below to test the property
            //modelInstance.lat shouldBe ("TODO")
        }

        // to test the property `lng`
        should("test lng") {
            // uncomment below to test the property
            //modelInstance.lng shouldBe ("TODO")
        }

    }
}
