/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.MobileAppBanner

class MobileAppBannerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MobileAppBanner
        //val modelInstance = MobileAppBanner()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `subtitle`
        should("test subtitle") {
            // uncomment below to test the property
            //modelInstance.subtitle shouldBe ("TODO")
        }

        // to test the property `imageUrl` - Full public URL of the banner image.
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `url` - Destination URL opened when the banner is tapped.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `thumbHash` - Base64-encoded ThumbHash of the banner image, for rendering a blurred  placeholder while the full image loads.
        should("test thumbHash") {
            // uncomment below to test the property
            //modelInstance.thumbHash shouldBe ("TODO")
        }

    }
}
