/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.OverviewRuns

class OverviewRunsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OverviewRuns
        //val modelInstance = OverviewRuns()

        // to test the property `total` - Total number of runs at the resort.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When the most recent update to run status was made.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property ``open`` - Number of runs currently open.  Not included if the runs status feature is disabled.
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `groomed` - Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled.
        should("test groomed") {
            // uncomment below to test the property
            //modelInstance.groomed shouldBe ("TODO")
        }

        // to test the property `openAcres` - Total acres of open runs.  Not included if acres are not tracked or the runs status feature is disabled.
        should("test openAcres") {
            // uncomment below to test the property
            //modelInstance.openAcres shouldBe ("TODO")
        }

        // to test the property `totalAcres` - Total acres of all runs.  Not included if acres are not tracked.
        should("test totalAcres") {
            // uncomment below to test the property
            //modelInstance.totalAcres shouldBe ("TODO")
        }

    }
}
