/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.OverviewSummerTrails

class OverviewSummerTrailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OverviewSummerTrails
        //val modelInstance = OverviewSummerTrails()

        // to test the property `total` - Total number of summer trails at the resort.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When the most recent update to summer trail status was made.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property ``open`` - Number of summer trails currently open.  Not included if the summer trails status feature is disabled.
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

    }
}
