/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.Overview
import com.mtnmanager.sdk.models.OverviewLifts
import com.mtnmanager.sdk.models.OverviewNews
import com.mtnmanager.sdk.models.OverviewRuns
import com.mtnmanager.sdk.models.OverviewSummerTrails
import com.mtnmanager.sdk.models.OverviewTerrainParks
import com.mtnmanager.sdk.models.ResortStatus
import com.mtnmanager.sdk.models.SeasonType

class OverviewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Overview
        //val modelInstance = Overview()

        // to test the property `status` - Current operational status of the resort (open or closed).  This is calculated based on the current time relative to today's scheduled hours.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `season` - Current operating season (winter, summer, or closed/off-season).
        should("test season") {
            // uncomment below to test the property
            //modelInstance.season shouldBe ("TODO")
        }

        // to test the property `news` - Written news — daily update, announcements, etc.
        should("test news") {
            // uncomment below to test the property
            //modelInstance.news shouldBe ("TODO")
        }

        // to test the property `runs` - Run statistics: counts, acres, and last-updated timestamp.
        should("test runs") {
            // uncomment below to test the property
            //modelInstance.runs shouldBe ("TODO")
        }

        // to test the property `lifts` - Lift statistics: counts and last-updated timestamp.
        should("test lifts") {
            // uncomment below to test the property
            //modelInstance.lifts shouldBe ("TODO")
        }

        // to test the property `summerTrails` - Summer trail statistics: counts and last-updated timestamp.
        should("test summerTrails") {
            // uncomment below to test the property
            //modelInstance.summerTrails shouldBe ("TODO")
        }

        // to test the property `terrainParks` - Terrain park statistics: counts and last-updated timestamp.
        should("test terrainParks") {
            // uncomment below to test the property
            //modelInstance.terrainParks shouldBe ("TODO")
        }

        // to test the property `opensAt` - Today's scheduled opening time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today.
        should("test opensAt") {
            // uncomment below to test the property
            //modelInstance.opensAt shouldBe ("TODO")
        }

        // to test the property `closesAt` - Today's scheduled closing time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today.
        should("test closesAt") {
            // uncomment below to test the property
            //modelInstance.closesAt shouldBe ("TODO")
        }

    }
}
