/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.OverviewNews

class OverviewNewsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OverviewNews
        //val modelInstance = OverviewNews()

        // to test the property `uuid` - Stable identifier of this news feed.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `isPrimary` - Whether this is the resort's primary news feed. Exactly one news is.
        should("test isPrimary") {
            // uncomment below to test the property
            //modelInstance.isPrimary shouldBe ("TODO")
        }

        // to test the property `raw` - Markdown source. Images the resort uploaded point at their public URLs,  so any Markdown renderer can display them.
        should("test raw") {
            // uncomment below to test the property
            //modelInstance.raw shouldBe ("TODO")
        }

        // to test the property `html` - Rendered HTML (from Markdown)
        should("test html") {
            // uncomment below to test the property
            //modelInstance.html shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When the news was last updated.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `name` - The name the resort gave this news feed, for telling several apart.  May be `null` on the primary news feed.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
