/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.ParkingLot
import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.ParkingLotStatus

class ParkingLotTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ParkingLot
        //val modelInstance = ParkingLot()

        // to test the property `uuid` - Unique identifier for the parking lot.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name` - Display name of the parking lot.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug` - URL-friendly name of the parking lot.
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `status` - Current status (open, closed, or full).
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `shuttle` - Whether shuttle service is available from this lot.
        should("test shuttle") {
            // uncomment below to test the property
            //modelInstance.shuttle shouldBe ("TODO")
        }

        // to test the property `paid` - Whether parking is paid/requires payment.
        should("test paid") {
            // uncomment below to test the property
            //modelInstance.paid shouldBe ("TODO")
        }

        // to test the property `reservationRequired` - Whether a reservation is required to park here.
        should("test reservationRequired") {
            // uncomment below to test the property
            //modelInstance.reservationRequired shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When this parking lot's information was last updated.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `capacity` - Maximum vehicle capacity, if set.
        should("test capacity") {
            // uncomment below to test the property
            //modelInstance.capacity shouldBe ("TODO")
        }

        // to test the property `images` - Images attached to this parking lot, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

    }
}
