/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.PathUuid

class PathUuidTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PathUuid
        //val modelInstance = PathUuid()

        // to test the property `uuid` - Resource UUID
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

    }
}
