/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.ResortInfo
import com.mtnmanager.sdk.models.Region
import com.mtnmanager.sdk.models.UnitPreference

class ResortInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResortInfo
        //val modelInstance = ResortInfo()

        // to test the property `uuid` - Unique identifier for the resort.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name` - Display name of the resort.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug` - URL-friendly identifier for the resort, used in account subdomain.
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `timezone` - IANA timezone identifier for the resort's local time.
        should("test timezone") {
            // uncomment below to test the property
            //modelInstance.timezone shouldBe ("TODO")
        }

        // to test the property `region` - Region, affects difficulty icon style.
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `unitPreference` - Preferred unit system for measurements (metric or imperial).
        should("test unitPreference") {
            // uncomment below to test the property
            //modelInstance.unitPreference shouldBe ("TODO")
        }

        // to test the property `logoUrl` - Full public URL to the resort's logo image. `null` if no logo is set.
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

    }
}
