/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.Schedule
import com.mtnmanager.sdk.models.DayOfWeek

class ScheduleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Schedule
        //val modelInstance = Schedule()

        // to test the property `daysString` - Human-readable description of which days this schedule applies to.  Examples: \"Daily\", \"Saturday & Sunday\", \"Monday, Wednesday, and Friday\"
        should("test daysString") {
            // uncomment below to test the property
            //modelInstance.daysString shouldBe ("TODO")
        }

        // to test the property `daysOfWeek` - Array of days of the week this schedule applies to.  For programmatic use.
        should("test daysOfWeek") {
            // uncomment below to test the property
            //modelInstance.daysOfWeek shouldBe ("TODO")
        }

        // to test the property `timeString` - Human-readable time range.  Example: \"9:00 AM to 4:00 PM\"
        should("test timeString") {
            // uncomment below to test the property
            //modelInstance.timeString shouldBe ("TODO")
        }

        // to test the property `opensAt` - Opening time in 24-hour format (HH:MM), in resort's local timezone.
        should("test opensAt") {
            // uncomment below to test the property
            //modelInstance.opensAt shouldBe ("TODO")
        }

        // to test the property `closesAt` - Closing time in 24-hour format (HH:MM), in resort's local timezone.
        should("test closesAt") {
            // uncomment below to test the property
            //modelInstance.closesAt shouldBe ("TODO")
        }

        // to test the property `inEffect` - Whether this schedule is currently in effect.  `false` for upcoming schedules that haven't started yet.
        should("test inEffect") {
            // uncomment below to test the property
            //modelInstance.inEffect shouldBe ("TODO")
        }

        // to test the property `effectiveString` - Human-readable date range when this schedule is effective.  Example: \"November 1, 2024 to April 15, 2025\"
        should("test effectiveString") {
            // uncomment below to test the property
            //modelInstance.effectiveString shouldBe ("TODO")
        }

        // to test the property `effectiveFrom` - Start date of the effective period (YYYY-MM-DD).
        should("test effectiveFrom") {
            // uncomment below to test the property
            //modelInstance.effectiveFrom shouldBe ("TODO")
        }

        // to test the property `effectiveTo` - End date of the effective period (YYYY-MM-DD).
        should("test effectiveTo") {
            // uncomment below to test the property
            //modelInstance.effectiveTo shouldBe ("TODO")
        }

    }
}
