/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.SeasonPeriod
import com.mtnmanager.sdk.models.SeasonType

class SeasonPeriodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SeasonPeriod
        //val modelInstance = SeasonPeriod()

        // to test the property `seasonType` - The season's type (`winter` or `summer`; never `closed`).
        should("test seasonType") {
            // uncomment below to test the property
            //modelInstance.seasonType shouldBe ("TODO")
        }

        // to test the property `startsOn` - The season's first day (YYYY-MM-DD), in the resort's local timezone.
        should("test startsOn") {
            // uncomment below to test the property
            //modelInstance.startsOn shouldBe ("TODO")
        }

        // to test the property `endsOn` - The season's last day (YYYY-MM-DD), in the resort's local timezone.
        should("test endsOn") {
            // uncomment below to test the property
            //modelInstance.endsOn shouldBe ("TODO")
        }

    }
}
