/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.SnowReport
import com.mtnmanager.sdk.models.SnowMetrics
import com.mtnmanager.sdk.models.SurfaceCondition

class SnowReportTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SnowReport
        //val modelInstance = SnowReport()

        // to test the property `uuid` - Unique identifier for this snow report.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `conditionNotes` - Additional notes about current snow conditions, e.g. groomer's notes
        should("test conditionNotes") {
            // uncomment below to test the property
            //modelInstance.conditionNotes shouldBe ("TODO")
        }

        // to test the property `snowfallCm` - Snowfall accumulation metrics in centimeters.
        should("test snowfallCm") {
            // uncomment below to test the property
            //modelInstance.snowfallCm shouldBe ("TODO")
        }

        // to test the property `snowfallIn` - Snowfall accumulation metrics in inches.
        should("test snowfallIn") {
            // uncomment below to test the property
            //modelInstance.snowfallIn shouldBe ("TODO")
        }

        // to test the property `reportedAt` - When this snow report was last updated.
        should("test reportedAt") {
            // uncomment below to test the property
            //modelInstance.reportedAt shouldBe ("TODO")
        }

        // to test the property `areaUuid` - UUID of the area this report covers, if area-specific.  `null` for resort-wide reports.
        should("test areaUuid") {
            // uncomment below to test the property
            //modelInstance.areaUuid shouldBe ("TODO")
        }

        // to test the property `areaName` - Name of the area this report covers, if area-specific.
        should("test areaName") {
            // uncomment below to test the property
            //modelInstance.areaName shouldBe ("TODO")
        }

        // to test the property `areaDisplayOrder` - Display order of the area this report covers, if area-specific, for sorting purposes.
        should("test areaDisplayOrder") {
            // uncomment below to test the property
            //modelInstance.areaDisplayOrder shouldBe ("TODO")
        }

        // to test the property `baseDepthCm` - Current base depth in centimeters.  Not included if the base depth feature is disabled.
        should("test baseDepthCm") {
            // uncomment below to test the property
            //modelInstance.baseDepthCm shouldBe ("TODO")
        }

        // to test the property `baseDepthIn` - Current base depth in inches.  Not included if the base depth feature is disabled.
        should("test baseDepthIn") {
            // uncomment below to test the property
            //modelInstance.baseDepthIn shouldBe ("TODO")
        }

        // to test the property `surfaceCondition` - Primary surface condition using industry standard codes.  Not included if the snow surface condition feature is disabled.   - BS (Bare Spots)  - CO (Corn Snow)  - FG (Frozen Granular)  - HP (Hard Pack)  - IP (Ice Patches)  - IS (Icy Surface)  - LG (Loose Granular)  - MG (Machine Groomed)  - P (Powder)  - PP (Packed Powder)  - SC (Spring Conditions)  - TC (Thin Cover)  - V (Variable)  - WG (Wet Granular)  - WP (Wet Powder)
        should("test surfaceCondition") {
            // uncomment below to test the property
            //modelInstance.surfaceCondition shouldBe ("TODO")
        }

        // to test the property `secondarySurfaceCondition` - Secondary surface condition using industry standard codes.  Not included if the secondary snow surface condition feature is disabled.   - BS (Bare Spots)  - CO (Corn Snow)  - FG (Frozen Granular)  - HP (Hard Pack)  - IP (Ice Patches)  - IS (Icy Surface)  - LG (Loose Granular)  - MG (Machine Groomed)  - P (Powder)  - PP (Packed Powder)  - SC (Spring Conditions)  - TC (Thin Cover)  - V (Variable)  - WG (Wet Granular)  - WP (Wet Powder)
        should("test secondarySurfaceCondition") {
            // uncomment below to test the property
            //modelInstance.secondarySurfaceCondition shouldBe ("TODO")
        }

    }
}
