/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TerrainParkFeature
import com.mtnmanager.sdk.models.EntityImage
import com.mtnmanager.sdk.models.FeatureSize
import com.mtnmanager.sdk.models.FeatureType
import com.mtnmanager.sdk.models.TerrainParkFeatureStatus

class TerrainParkFeatureTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TerrainParkFeature
        //val modelInstance = TerrainParkFeature()

        // to test the property `uuid` - Unique identifier for the feature.
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name` - Display name of the feature.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug` - URL-friendly name of the run.
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `featureType` - Type of feature (jump, box, rail, other).
        should("test featureType") {
            // uncomment below to test the property
            //modelInstance.featureType shouldBe ("TODO")
        }

        // to test the property `status` - Current operational status (open, closed, or unknown).  `unknown` unless the terrain park feature status is enabled.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `number` - Optional feature number.
        should("test number") {
            // uncomment below to test the property
            //modelInstance.number shouldBe ("TODO")
        }

        // to test the property `propertySize` - Optional size rating of the feature (S, M, L, XL).
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `images` - Images attached to this feature, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads.
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

    }
}
