/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMapStaticElement
import com.mtnmanager.sdk.models.GeometryMode
import com.mtnmanager.sdk.models.LabelOffset
import com.mtnmanager.sdk.models.MarkerIcon
import com.mtnmanager.sdk.models.TrailMapElementOneOf7
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf1
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf2
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf3
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf4
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf5
import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf6

class TrailMapStaticElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMapStaticElement
        //val modelInstance = TrailMapStaticElement()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `points`
        should("test points") {
            // uncomment below to test the property
            //modelInstance.points shouldBe ("TODO")
        }

        // to test the property `liftUuid`
        should("test liftUuid") {
            // uncomment below to test the property
            //modelInstance.liftUuid shouldBe ("TODO")
        }

        // to test the property `runUuid`
        should("test runUuid") {
            // uncomment below to test the property
            //modelInstance.runUuid shouldBe ("TODO")
        }

        // to test the property `terrainParkUuid`
        should("test terrainParkUuid") {
            // uncomment below to test the property
            //modelInstance.terrainParkUuid shouldBe ("TODO")
        }

        // to test the property `summerTrailUuid`
        should("test summerTrailUuid") {
            // uncomment below to test the property
            //modelInstance.summerTrailUuid shouldBe ("TODO")
        }

        // to test the property `x`
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y`
        should("test y") {
            // uncomment below to test the property
            //modelInstance.y shouldBe ("TODO")
        }

        // to test the property `amenityUuid`
        should("test amenityUuid") {
            // uncomment below to test the property
            //modelInstance.amenityUuid shouldBe ("TODO")
        }

        // to test the property `parkingLotUuid`
        should("test parkingLotUuid") {
            // uncomment below to test the property
            //modelInstance.parkingLotUuid shouldBe ("TODO")
        }

        // to test the property `webcamUuid`
        should("test webcamUuid") {
            // uncomment below to test the property
            //modelInstance.webcamUuid shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `tension`
        should("test tension") {
            // uncomment below to test the property
            //modelInstance.tension shouldBe ("TODO")
        }

        // to test the property `geometry`
        should("test geometry") {
            // uncomment below to test the property
            //modelInstance.geometry shouldBe ("TODO")
        }

        // to test the property `labelOffset`
        should("test labelOffset") {
            // uncomment below to test the property
            //modelInstance.labelOffset shouldBe ("TODO")
        }

        // to test the property `icon`
        should("test icon") {
            // uncomment below to test the property
            //modelInstance.icon shouldBe ("TODO")
        }

        // to test the property `color`
        should("test color") {
            // uncomment below to test the property
            //modelInstance.color shouldBe ("TODO")
        }

        // to test the property `groupLabel`
        should("test groupLabel") {
            // uncomment below to test the property
            //modelInstance.groupLabel shouldBe ("TODO")
        }

        // to test the property `searchable`
        should("test searchable") {
            // uncomment below to test the property
            //modelInstance.searchable shouldBe ("TODO")
        }

    }
}
