/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMapStaticElementOneOf1
import com.mtnmanager.sdk.models.GeometryMode
import com.mtnmanager.sdk.models.LabelOffset

class TrailMapStaticElementOneOf1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMapStaticElementOneOf1
        //val modelInstance = TrailMapStaticElementOneOf1()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `points`
        should("test points") {
            // uncomment below to test the property
            //modelInstance.points shouldBe ("TODO")
        }

        // to test the property `runUuid`
        should("test runUuid") {
            // uncomment below to test the property
            //modelInstance.runUuid shouldBe ("TODO")
        }

        // to test the property `tension`
        should("test tension") {
            // uncomment below to test the property
            //modelInstance.tension shouldBe ("TODO")
        }

        // to test the property `geometry`
        should("test geometry") {
            // uncomment below to test the property
            //modelInstance.geometry shouldBe ("TODO")
        }

        // to test the property `labelOffset`
        should("test labelOffset") {
            // uncomment below to test the property
            //modelInstance.labelOffset shouldBe ("TODO")
        }

    }
}
