/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMapSummary
import com.mtnmanager.sdk.models.GeoBounds
import com.mtnmanager.sdk.models.SeasonType

class TrailMapSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMapSummary
        //val modelInstance = TrailMapSummary()

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `season`
        should("test season") {
            // uncomment below to test the property
            //modelInstance.season shouldBe ("TODO")
        }

        // to test the property `displayOrder`
        should("test displayOrder") {
            // uncomment below to test the property
            //modelInstance.displayOrder shouldBe ("TODO")
        }

        // to test the property `version` - Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `hostedUrl`
        should("test hostedUrl") {
            // uncomment below to test the property
            //modelInstance.hostedUrl shouldBe ("TODO")
        }

        // to test the property `entityUuids` - Deduplicated UUIDs of every entity (lift, run, terrain park,  summer trail, amenity, parking lot) referenced by this map's elements.
        should("test entityUuids") {
            // uncomment below to test the property
            //modelInstance.entityUuids shouldBe ("TODO")
        }

        // to test the property `geoBounds` - Lat/lng bounding box of this map's georeferenced area, plus the  centroid of its control points (used for tie-breaking when multiple  maps cover the same point). Omitted when the map has no georeferencing.
        should("test geoBounds") {
            // uncomment below to test the property
            //modelInstance.geoBounds shouldBe ("TODO")
        }

    }
}
