/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMapElement
import com.mtnmanager.sdk.models.Amenity
import com.mtnmanager.sdk.models.LabelOffset
import com.mtnmanager.sdk.models.Lift
import com.mtnmanager.sdk.models.MarkerIcon
import com.mtnmanager.sdk.models.ParkingLot
import com.mtnmanager.sdk.models.Run
import com.mtnmanager.sdk.models.SummerTrail
import com.mtnmanager.sdk.models.TerrainPark
import com.mtnmanager.sdk.models.TrailMapElementOneOf
import com.mtnmanager.sdk.models.TrailMapElementOneOf1
import com.mtnmanager.sdk.models.TrailMapElementOneOf2
import com.mtnmanager.sdk.models.TrailMapElementOneOf3
import com.mtnmanager.sdk.models.TrailMapElementOneOf4
import com.mtnmanager.sdk.models.TrailMapElementOneOf5
import com.mtnmanager.sdk.models.TrailMapElementOneOf6
import com.mtnmanager.sdk.models.TrailMapElementOneOf7
import com.mtnmanager.sdk.models.Webcam

class TrailMapElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMapElement
        //val modelInstance = TrailMapElement()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `points`
        should("test points") {
            // uncomment below to test the property
            //modelInstance.points shouldBe ("TODO")
        }

        // to test the property `x`
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y`
        should("test y") {
            // uncomment below to test the property
            //modelInstance.y shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `tension`
        should("test tension") {
            // uncomment below to test the property
            //modelInstance.tension shouldBe ("TODO")
        }

        // to test the property `lift`
        should("test lift") {
            // uncomment below to test the property
            //modelInstance.lift shouldBe ("TODO")
        }

        // to test the property `run`
        should("test run") {
            // uncomment below to test the property
            //modelInstance.run shouldBe ("TODO")
        }

        // to test the property `labelOffset`
        should("test labelOffset") {
            // uncomment below to test the property
            //modelInstance.labelOffset shouldBe ("TODO")
        }

        // to test the property `terrainPark`
        should("test terrainPark") {
            // uncomment below to test the property
            //modelInstance.terrainPark shouldBe ("TODO")
        }

        // to test the property `summerTrail`
        should("test summerTrail") {
            // uncomment below to test the property
            //modelInstance.summerTrail shouldBe ("TODO")
        }

        // to test the property `icon`
        should("test icon") {
            // uncomment below to test the property
            //modelInstance.icon shouldBe ("TODO")
        }

        // to test the property `color`
        should("test color") {
            // uncomment below to test the property
            //modelInstance.color shouldBe ("TODO")
        }

        // to test the property `amenity`
        should("test amenity") {
            // uncomment below to test the property
            //modelInstance.amenity shouldBe ("TODO")
        }

        // to test the property `groupLabel`
        should("test groupLabel") {
            // uncomment below to test the property
            //modelInstance.groupLabel shouldBe ("TODO")
        }

        // to test the property `parkingLot`
        should("test parkingLot") {
            // uncomment below to test the property
            //modelInstance.parkingLot shouldBe ("TODO")
        }

        // to test the property `webcam`
        should("test webcam") {
            // uncomment below to test the property
            //modelInstance.webcam shouldBe ("TODO")
        }

        // to test the property `searchable`
        should("test searchable") {
            // uncomment below to test the property
            //modelInstance.searchable shouldBe ("TODO")
        }

    }
}
