/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMapElementOneOf7
import com.mtnmanager.sdk.models.MarkerIcon

class TrailMapElementOneOf7Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMapElementOneOf7
        //val modelInstance = TrailMapElementOneOf7()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `x`
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y`
        should("test y") {
            // uncomment below to test the property
            //modelInstance.y shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `icon`
        should("test icon") {
            // uncomment below to test the property
            //modelInstance.icon shouldBe ("TODO")
        }

        // to test the property `color`
        should("test color") {
            // uncomment below to test the property
            //modelInstance.color shouldBe ("TODO")
        }

        // to test the property `searchable`
        should("test searchable") {
            // uncomment below to test the property
            //modelInstance.searchable shouldBe ("TODO")
        }

        // to test the property `groupLabel`
        should("test groupLabel") {
            // uncomment below to test the property
            //modelInstance.groupLabel shouldBe ("TODO")
        }

    }
}
