/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMapElementOneOf3
import com.mtnmanager.sdk.models.SummerTrail

class TrailMapElementOneOf3Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMapElementOneOf3
        //val modelInstance = TrailMapElementOneOf3()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `points`
        should("test points") {
            // uncomment below to test the property
            //modelInstance.points shouldBe ("TODO")
        }

        // to test the property `tension`
        should("test tension") {
            // uncomment below to test the property
            //modelInstance.tension shouldBe ("TODO")
        }

        // to test the property `summerTrail`
        should("test summerTrail") {
            // uncomment below to test the property
            //modelInstance.summerTrail shouldBe ("TODO")
        }

    }
}
