/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.TrailMap
import com.mtnmanager.sdk.models.GeoControlPoint
import com.mtnmanager.sdk.models.ResortInfo
import com.mtnmanager.sdk.models.SeasonType
import com.mtnmanager.sdk.models.TrailMapElement

class TrailMapTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TrailMap
        //val modelInstance = TrailMap()

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `season`
        should("test season") {
            // uncomment below to test the property
            //modelInstance.season shouldBe ("TODO")
        }

        // to test the property `displayOrder`
        should("test displayOrder") {
            // uncomment below to test the property
            //modelInstance.displayOrder shouldBe ("TODO")
        }

        // to test the property `version` - Monotonically incremented on every update. Clients can compare this  against a cached value to decide whether to reload the trail map.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `backgroundImageUrl`
        should("test backgroundImageUrl") {
            // uncomment below to test the property
            //modelInstance.backgroundImageUrl shouldBe ("TODO")
        }

        // to test the property `resort`
        should("test resort") {
            // uncomment below to test the property
            //modelInstance.resort shouldBe ("TODO")
        }

        // to test the property `elements`
        should("test elements") {
            // uncomment below to test the property
            //modelInstance.elements shouldBe ("TODO")
        }

        // to test the property `geoControlPoints`
        should("test geoControlPoints") {
            // uncomment below to test the property
            //modelInstance.geoControlPoints shouldBe ("TODO")
        }

    }
}
