/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.Weather
import com.mtnmanager.sdk.models.CurrentWeather
import com.mtnmanager.sdk.models.DailyForecast
import com.mtnmanager.sdk.models.HourlyForecast

class WeatherTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Weather
        //val modelInstance = Weather()

        // to test the property `current` - Current weather conditions
        should("test current") {
            // uncomment below to test the property
            //modelInstance.current shouldBe ("TODO")
        }

        // to test the property `hourlyForecast` - Hourly forecast for next 24 hours (including current hour)
        should("test hourlyForecast") {
            // uncomment below to test the property
            //modelInstance.hourlyForecast shouldBe ("TODO")
        }

        // to test the property `dailyForecast` - Daily forecast for next 7 days (including today)
        should("test dailyForecast") {
            // uncomment below to test the property
            //modelInstance.dailyForecast shouldBe ("TODO")
        }

        // to test the property `attribution` - Data source attribution
        should("test attribution") {
            // uncomment below to test the property
            //modelInstance.attribution shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When this data was last updated
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `areaUuid` - The area this weather belongs to, or omitted for resort-wide weather.
        should("test areaUuid") {
            // uncomment below to test the property
            //modelInstance.areaUuid shouldBe ("TODO")
        }

        // to test the property `areaName` - The area's name, or omitted for resort-wide weather.
        should("test areaName") {
            // uncomment below to test the property
            //modelInstance.areaName shouldBe ("TODO")
        }

        // to test the property `areaDisplayOrder` - The area's display order, or omitted for resort-wide weather.
        should("test areaDisplayOrder") {
            // uncomment below to test the property
            //modelInstance.areaDisplayOrder shouldBe ("TODO")
        }

    }
}
