/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.WebcamHistoryResponse
import com.mtnmanager.sdk.models.WebcamHistoryFrame

class WebcamHistoryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebcamHistoryResponse
        //val modelInstance = WebcamHistoryResponse()

        // to test the property `webcamUuid`
        should("test webcamUuid") {
            // uncomment below to test the property
            //modelInstance.webcamUuid shouldBe ("TODO")
        }

        // to test the property `frames` - Newest first.
        should("test frames") {
            // uncomment below to test the property
            //modelInstance.frames shouldBe ("TODO")
        }

    }
}
