/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.mtnmanager.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.mtnmanager.sdk.models.Webcam

class WebcamTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Webcam
        //val modelInstance = Webcam()

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `latestImageUrl` - URL of the newest frame (refreshes within ~60s via the edge cache).
        should("test latestImageUrl") {
            // uncomment below to test the property
            //modelInstance.latestImageUrl shouldBe ("TODO")
        }

        // to test the property `latestDaylightImageUrl` - URL of the last daylight frame.
        should("test latestDaylightImageUrl") {
            // uncomment below to test the property
            //modelInstance.latestDaylightImageUrl shouldBe ("TODO")
        }

        // to test the property `latestThumbUrl`
        should("test latestThumbUrl") {
            // uncomment below to test the property
            //modelInstance.latestThumbUrl shouldBe ("TODO")
        }

        // to test the property `latestDaylightThumbUrl`
        should("test latestDaylightThumbUrl") {
            // uncomment below to test the property
            //modelInstance.latestDaylightThumbUrl shouldBe ("TODO")
        }

        // to test the property `latestThumbhash` - ThumbHash of the `latest` frame (standard base64) — a compact blur  placeholder to render while the image loads. Empty string until the first  frame (or on cameras predating the feature).
        should("test latestThumbhash") {
            // uncomment below to test the property
            //modelInstance.latestThumbhash shouldBe ("TODO")
        }

        // to test the property `latestDaylightThumbhash` - ThumbHash of the `latest-daylight` frame (standard base64). Empty string  until the first daylight frame.
        should("test latestDaylightThumbhash") {
            // uncomment below to test the property
            //modelInstance.latestDaylightThumbhash shouldBe ("TODO")
        }

        // to test the property `hasHistory` - Whether this camera archives frames — i.e. whether its history endpoint  returns anything. When `false`, don't call the history API for it.
        should("test hasHistory") {
            // uncomment below to test the property
            //modelInstance.hasHistory shouldBe ("TODO")
        }

        // to test the property `areaUuid`
        should("test areaUuid") {
            // uncomment below to test the property
            //modelInstance.areaUuid shouldBe ("TODO")
        }

        // to test the property `areaName`
        should("test areaName") {
            // uncomment below to test the property
            //modelInstance.areaName shouldBe ("TODO")
        }

        // to test the property `areaDisplayOrder`
        should("test areaDisplayOrder") {
            // uncomment below to test the property
            //modelInstance.areaDisplayOrder shouldBe ("TODO")
        }

        // to test the property `elevationFt` - Camera elevation in both units; omitted when unset.
        should("test elevationFt") {
            // uncomment below to test the property
            //modelInstance.elevationFt shouldBe ("TODO")
        }

        // to test the property `elevationM`
        should("test elevationM") {
            // uncomment below to test the property
            //modelInstance.elevationM shouldBe ("TODO")
        }

        // to test the property `lastFrameAt` - Time of the most recently published frame; omitted until the first frame.
        should("test lastFrameAt") {
            // uncomment below to test the property
            //modelInstance.lastFrameAt shouldBe ("TODO")
        }

    }
}
